;; this will be glew+opengl
(module (egggame glew) *

(import (scheme)
        (chicken base)
        (chicken syntax)
        (chicken module)
        (chicken foreign)
        (srfi-4))

(foreign-declare "#include <GL/glew.h>")

(define-foreign-type GLenum unsigned-int)

;; =============================================================================
;; errors
;; =============================================================================

(define GL_NO_ERROR (foreign-value "GL_NO_ERROR" GLenum))
(define GL_INVALID_ENUM (foreign-value "GL_INVALID_ENUM" GLenum))
(define GL_INVALID_VALUE (foreign-value "GL_INVALID_VALUE" GLenum))
(define GL_INVALID_OPERATION (foreign-value "GL_INVALID_OPERATION" GLenum))
(define GL_INVALID_FRAMEBUFFER_OPERATION (foreign-value "GL_INVALID_FRAMEBUFFER_OPERATION" GLenum))
(define GL_OUT_OF_MEMORY (foreign-value "GL_OUT_OF_MEMORY" GLenum))
(define GL_STACK_UNDERFLOW (foreign-value "GL_STACK_UNDERFLOW" GLenum))
(define GL_STACK_OVERFLOW (foreign-value "GL_STACK_OVERFLOW" GLenum))

(define glGetError (foreign-lambda GLenum glGetError))
(define gluErrorString (foreign-lambda c-string gluErrorString GLenum))

;; =============================================================================
;; buffers
;; =============================================================================

;; buffer types
(define GL_ARRAY_BUFFER (foreign-value "GL_ARRAY_BUFFER" GLenum))
(define GL_ATOMIC_COUNTER_BUFFER (foreign-value "GL_ATOMIC_COUNTER_BUFFER" GLenum))
(define GL_COPY_READ_BUFFER (foreign-value "GL_COPY_READ_BUFFER" GLenum))
(define GL_COPY_WRITE_BUFFER (foreign-value "GL_COPY_WRITE_BUFFER" GLenum))
(define GL_DISPATCH_INDIRECT_BUFFER (foreign-value "GL_DISPATCH_INDIRECT_BUFFER" GLenum))
(define GL_DRAW_INDIRECT_BUFFER (foreign-value "GL_DRAW_INDIRECT_BUFFER" GLenum))
(define GL_ELEMENT_ARRAY_BUFFER (foreign-value "GL_ELEMENT_ARRAY_BUFFER" GLenum))
(define GL_PIXEL_PACK_BUFFER (foreign-value "GL_PIXEL_PACK_BUFFER" GLenum))
(define GL_PIXEL_UNPACK_BUFFER (foreign-value "GL_PIXEL_UNPACK_BUFFER" GLenum))
(define GL_QUERY_BUFFER (foreign-value "GL_QUERY_BUFFER" GLenum))
(define GL_SHADER_STORAGE_BUFFER (foreign-value "GL_SHADER_STORAGE_BUFFER" GLenum))
(define GL_TEXTURE_BUFFER (foreign-value "GL_TEXTURE_BUFFER" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER" GLenum))
(define GL_UNIFORM_BUFFER (foreign-value "GL_UNIFORM_BUFFER" GLenum))

;; buffer usages
(define GL_STREAM_DRAW (foreign-value "GL_STREAM_DRAW" GLenum))
(define GL_STREAM_READ (foreign-value "GL_STREAM_READ" GLenum))
(define GL_STREAM_COPY (foreign-value "GL_STREAM_COPY" GLenum))
(define GL_STATIC_DRAW (foreign-value "GL_STATIC_DRAW" GLenum))
(define GL_STATIC_READ (foreign-value "GL_STATIC_READ" GLenum))
(define GL_STATIC_COPY (foreign-value "GL_STATIC_COPY" GLenum))
(define GL_DYNAMIC_DRAW (foreign-value "GL_DYNAMIC_DRAW" GLenum))
(define GL_DYNAMIC_READ (foreign-value "GL_DYNAMIC_READ" GLenum))
(define GL_DYNAMIC_COPY (foreign-value "GL_DYNAMIC_COPY" GLenum))

;; funcs
(define glGenBuffers (foreign-lambda void glGenBuffers size_t u32vector))
(define glBindBuffer (foreign-lambda void glBindBuffer GLenum unsigned-int))
(define glBufferData (foreign-lambda void glBufferData GLenum unsigned-integer64 c-pointer GLenum))
(define glDeleteBuffers (foreign-lambda void glDeleteBuffers size_t u32vector))

;; =============================================================================
;; textures
;; =============================================================================

;; targets
(define GL_TEXTURE_1D (foreign-value "GL_TEXTURE_1D" GLenum))
(define GL_TEXTURE_1D_ARRAY (foreign-value "GL_TEXTURE_1D_ARRAY" GLenum))
(define GL_TEXTURE_2D (foreign-value "GL_TEXTURE_2D" GLenum))
(define GL_TEXTURE_2D_ARRAY (foreign-value "GL_TEXTURE_2D_ARRAY" GLenum))
(define GL_TEXTURE_2D_MULTISAMPLE (foreign-value "GL_TEXTURE_2D_MULTISAMPLE" GLenum))
(define GL_TEXTURE_2D_MULTISAMPLE_ARRAY (foreign-value "GL_TEXTURE_2D_MULTISAMPLE_ARRAY" GLenum))
(define GL_TEXTURE_3D (foreign-value "GL_TEXTURE_3D" GLenum))
(define GL_TEXTURE_CUBE_MAP (foreign-value "GL_TEXTURE_CUBE_MAP" GLenum))
(define GL_TEXTURE_CUBE_MAP_ARRAY (foreign-value "GL_TEXTURE_CUBE_MAP_ARRAY" GLenum))
(define GL_TEXTURE_RECTANGLE (foreign-value "GL_TEXTURE_RECTANGLE" GLenum))

;; pnames
(define GL_DEPTH_STENCIL_TEXTURE_MODE (foreign-value "GL_DEPTH_STENCIL_TEXTURE_MODE" GLenum))
(define GL_TEXTURE_BASE_LEVEL (foreign-value "GL_TEXTURE_BASE_LEVEL" GLenum))
(define GL_TEXTURE_COMPARE_FUNC (foreign-value "GL_TEXTURE_COMPARE_FUNC" GLenum))
(define GL_TEXTURE_COMPARE_MODE (foreign-value "GL_TEXTURE_COMPARE_MODE" GLenum))
(define GL_TEXTURE_LOD_BIAS (foreign-value "GL_TEXTURE_LOD_BIAS" GLenum))
(define GL_TEXTURE_MIN_FILTER (foreign-value "GL_TEXTURE_MIN_FILTER" GLenum))
(define GL_TEXTURE_MAG_FILTER (foreign-value "GL_TEXTURE_MAG_FILTER" GLenum))
(define GL_TEXTURE_MIN_LOD (foreign-value "GL_TEXTURE_MIN_LOD" GLenum))
(define GL_TEXTURE_MAX_LOD (foreign-value "GL_TEXTURE_MAX_LOD" GLenum))
(define GL_TEXTURE_MAX_LEVEL (foreign-value "GL_TEXTURE_MAX_LEVEL" GLenum))
(define GL_TEXTURE_SWIZZLE_R (foreign-value "GL_TEXTURE_SWIZZLE_R" GLenum))
(define GL_TEXTURE_SWIZZLE_G (foreign-value "GL_TEXTURE_SWIZZLE_G" GLenum))
(define GL_TEXTURE_SWIZZLE_B (foreign-value "GL_TEXTURE_SWIZZLE_B" GLenum))
(define GL_TEXTURE_SWIZZLE_A (foreign-value "GL_TEXTURE_SWIZZLE_A" GLenum))
(define GL_TEXTURE_WRAP_S (foreign-value "GL_TEXTURE_WRAP_S" GLenum))
(define GL_TEXTURE_WRAP_T (foreign-value "GL_TEXTURE_WRAP_T" GLenum))
(define GL_TEXTURE_WRAP_R (foreign-value "GL_TEXTURE_WRAP_R" GLenum))

;; internalFormats
(define GL_DEPTH_COMPONENT (foreign-value "GL_DEPTH_COMPONENT" GLenum))
(define GL_DEPTH_STENCIL (foreign-value "GL_DEPTH_STENCIL" GLenum))
(define GL_RED (foreign-value "GL_RED" GLenum))
(define GL_RG (foreign-value "GL_RG" GLenum))
(define GL_RGB (foreign-value "GL_RGB" GLenum))
(define GL_RGBA (foreign-value "GL_RGBA" GLenum))
(define GL_R8 (foreign-value "GL_R8" GLenum))
(define GL_R8_SNORM (foreign-value "GL_R8_SNORM" GLenum))
(define GL_R16 (foreign-value "GL_R16" GLenum))
(define GL_R16_SNORM (foreign-value "GL_R16_SNORM" GLenum))
(define GL_RG8 (foreign-value "GL_RG8" GLenum))
(define GL_RG8_SNORM (foreign-value "GL_RG8_SNORM" GLenum))
(define GL_RG16 (foreign-value "GL_RG16" GLenum))
(define GL_RG16_SNORM (foreign-value "GL_RG16_SNORM" GLenum))
(define GL_R3_G3_B2 (foreign-value "GL_R3_G3_B2" GLenum))
(define GL_RGB4 (foreign-value "GL_RGB4" GLenum))
(define GL_RGB5 (foreign-value "GL_RGB5" GLenum))
(define GL_RGB8 (foreign-value "GL_RGB8" GLenum))
(define GL_RGB8_SNORM (foreign-value "GL_RGB8_SNORM" GLenum))
(define GL_RGB10 (foreign-value "GL_RGB10" GLenum))
(define GL_RGB12 (foreign-value "GL_RGB12" GLenum))
(define GL_RGB16_SNORM (foreign-value "GL_RGB16_SNORM" GLenum))
(define GL_RGBA2 (foreign-value "GL_RGBA2" GLenum))
(define GL_RGBA4 (foreign-value "GL_RGBA4" GLenum))
(define GL_RGB5_A1 (foreign-value "GL_RGB5_A1" GLenum))
(define GL_RGBA8 (foreign-value "GL_RGBA8" GLenum))
(define GL_RGBA8_SNORM (foreign-value "GL_RGBA8_SNORM" GLenum))
(define GL_RGB10_A2 (foreign-value "GL_RGB10_A2" GLenum))
(define GL_RGB10_A2UI (foreign-value "GL_RGB10_A2UI" GLenum))
(define GL_RGBA12 (foreign-value "GL_RGBA12" GLenum))
(define GL_RGBA16 (foreign-value "GL_RGBA16" GLenum))
(define GL_SRGB8 (foreign-value "GL_SRGB8" GLenum))
(define GL_SRGB8_ALPHA8 (foreign-value "GL_SRGB8_ALPHA8" GLenum))
(define GL_R16F (foreign-value "GL_R16F" GLenum))
(define GL_RG16F (foreign-value "GL_RG16F" GLenum))
(define GL_RGB16F (foreign-value "GL_RGB16F" GLenum))
(define GL_RGBA16F (foreign-value "GL_RGBA16F" GLenum))
(define GL_R32F (foreign-value "GL_R32F" GLenum))
(define GL_RG32F (foreign-value "GL_RG32F" GLenum))
(define GL_RGB32F (foreign-value "GL_RGB32F" GLenum))
(define GL_RGBA32F (foreign-value "GL_RGBA32F" GLenum))
(define GL_R11F_G11F_B10F (foreign-value "GL_R11F_G11F_B10F" GLenum))
(define GL_RGB9_E5 (foreign-value "GL_RGB9_E5" GLenum))
(define GL_R8I (foreign-value "GL_R8I" GLenum))
(define GL_R8UI (foreign-value "GL_R8UI" GLenum))
(define GL_R16I (foreign-value "GL_R16I" GLenum))
(define GL_R16UI (foreign-value "GL_R16UI" GLenum))
(define GL_R32I (foreign-value "GL_R32I" GLenum))
(define GL_R32UI (foreign-value "GL_R32UI" GLenum))
(define GL_RG8I (foreign-value "GL_RG8I" GLenum))
(define GL_RG8UI (foreign-value "GL_RG8UI" GLenum))
(define GL_RG16I (foreign-value "GL_RG16I" GLenum))
(define GL_RG16UI (foreign-value "GL_RG16UI" GLenum))
(define GL_RG32I (foreign-value "GL_RG32I" GLenum))
(define GL_RG32UI (foreign-value "GL_RG32UI" GLenum))
(define GL_RGB8I (foreign-value "GL_RGB8I" GLenum))
(define GL_RGB8UI (foreign-value "GL_RGB8UI" GLenum))
(define GL_RGB16I (foreign-value "GL_RGB16I" GLenum))
(define GL_RGB16UI (foreign-value "GL_RGB16UI" GLenum))
(define GL_RGB32I (foreign-value "GL_RGB32I" GLenum))
(define GL_RGB32UI (foreign-value "GL_RGB32UI" GLenum))
(define GL_RGBA8I (foreign-value "GL_RGBA8I" GLenum))
(define GL_RGBA8UI (foreign-value "GL_RGBA8UI" GLenum))
(define GL_RGBA16I (foreign-value "GL_RGBA16I" GLenum))
(define GL_RGBA16UI (foreign-value "GL_RGBA16UI" GLenum))
(define GL_RGBA32I (foreign-value "GL_RGBA32I" GLenum))
(define GL_RGBA32UI (foreign-value "GL_RGBA32UI" GLenum))
(define GL_COMPRESSED_RED (foreign-value "GL_COMPRESSED_RED" GLenum))
(define GL_COMPRESSED_RG (foreign-value "GL_COMPRESSED_RG" GLenum))
(define GL_COMPRESSED_RGB (foreign-value "GL_COMPRESSED_RGB" GLenum))
(define GL_COMPRESSED_RGBA (foreign-value "GL_COMPRESSED_RGBA" GLenum))
(define GL_COMPRESSED_SRGB (foreign-value "GL_COMPRESSED_SRGB" GLenum))
(define GL_COMPRESSED_SRGB_ALPHA (foreign-value "GL_COMPRESSED_SRGB_ALPHA" GLenum))
(define GL_COMPRESSED_RED_RGTC1 (foreign-value "GL_COMPRESSED_RED_RGTC1" GLenum))
(define GL_COMPRESSED_SIGNED_RED_RGTC1 (foreign-value "GL_COMPRESSED_SIGNED_RED_RGTC1" GLenum))
(define GL_COMPRESSED_RG_RGTC2 (foreign-value "GL_COMPRESSED_RG_RGTC2" GLenum))
(define GL_COMPRESSED_SIGNED_RG_RGTC2 (foreign-value "GL_COMPRESSED_SIGNED_RG_RGTC2" GLenum))
(define GL_COMPRESSED_RGBA_BPTC_UNORM (foreign-value "GL_COMPRESSED_RGBA_BPTC_UNORM" GLenum))
(define GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM (foreign-value "GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM" GLenum))
(define GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT (foreign-value "GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT" GLenum))
(define GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT (foreign-value "GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT" GLenum))

;; formats
(define GL_RED (foreign-value "GL_RED" GLenum))
(define GL_RG (foreign-value "GL_RG" GLenum))
(define GL_RGB (foreign-value "GL_RGB" GLenum))
(define GL_BGR (foreign-value "GL_BGR" GLenum))
(define GL_RGBA (foreign-value "GL_RGBA" GLenum))
(define GL_BGRA (foreign-value "GL_BGRA" GLenum))
(define GL_RED_INTEGER (foreign-value "GL_RED_INTEGER" GLenum))
(define GL_RG_INTEGER (foreign-value "GL_RG_INTEGER" GLenum))
(define GL_RGB_INTEGER (foreign-value "GL_RGB_INTEGER" GLenum))
(define GL_BGR_INTEGER (foreign-value "GL_BGR_INTEGER" GLenum))
(define GL_RGBA_INTEGER (foreign-value "GL_RGBA_INTEGER" GLenum))
(define GL_BGRA_INTEGER (foreign-value "GL_BGRA_INTEGER" GLenum))
(define GL_STENCIL_INDEX (foreign-value "GL_STENCIL_INDEX" GLenum))
(define GL_DEPTH_COMPONENT (foreign-value "GL_DEPTH_COMPONENT" GLenum))
(define GL_DEPTH_STENCIL (foreign-value "GL_DEPTH_STENCIL" GLenum))

;; types
(define GL_UNSIGNED_BYTE (foreign-value "GL_UNSIGNED_BYTE" GLenum))
(define GL_BYTE (foreign-value "GL_BYTE" GLenum))
(define GL_UNSIGNED_SHORT (foreign-value "GL_UNSIGNED_SHORT" GLenum))
(define GL_SHORT (foreign-value "GL_SHORT" GLenum))
(define GL_UNSIGNED_INT (foreign-value "GL_UNSIGNED_INT" GLenum))
(define GL_INT (foreign-value "GL_INT" GLenum))
(define GL_HALF_FLOAT (foreign-value "GL_HALF_FLOAT" GLenum))
(define GL_FLOAT (foreign-value "GL_FLOAT" GLenum))
(define GL_UNSIGNED_BYTE_3_3_2 (foreign-value "GL_UNSIGNED_BYTE_3_3_2" GLenum))
(define GL_UNSIGNED_BYTE_2_3_3_REV (foreign-value "GL_UNSIGNED_BYTE_2_3_3_REV" GLenum))
(define GL_UNSIGNED_SHORT_5_6_5 (foreign-value "GL_UNSIGNED_SHORT_5_6_5" GLenum))
(define GL_UNSIGNED_SHORT_5_6_5_REV (foreign-value "GL_UNSIGNED_SHORT_5_6_5_REV" GLenum))
(define GL_UNSIGNED_SHORT_4_4_4_4 (foreign-value "GL_UNSIGNED_SHORT_4_4_4_4" GLenum))
(define GL_UNSIGNED_SHORT_4_4_4_4_REV (foreign-value "GL_UNSIGNED_SHORT_4_4_4_4_REV" GLenum))
(define GL_UNSIGNED_SHORT_5_5_5_1 (foreign-value "GL_UNSIGNED_SHORT_5_5_5_1" GLenum))
(define GL_UNSIGNED_SHORT_1_5_5_5_REV (foreign-value "GL_UNSIGNED_SHORT_1_5_5_5_REV" GLenum))
(define GL_UNSIGNED_INT_8_8_8_8 (foreign-value "GL_UNSIGNED_INT_8_8_8_8" GLenum))
(define GL_UNSIGNED_INT_8_8_8_8_REV (foreign-value "GL_UNSIGNED_INT_8_8_8_8_REV" GLenum))
(define GL_UNSIGNED_INT_10_10_10_2 (foreign-value "GL_UNSIGNED_INT_10_10_10_2" GLenum))
(define GL_UNSIGNED_INT_2_10_10_10_REV (foreign-value "GL_UNSIGNED_INT_2_10_10_10_REV" GLenum))

;; mag and min filter values
(define GL_NEAREST (foreign-value "GL_NEAREST" GLenum))
(define GL_LINEAR (foreign-value "GL_LINEAR" GLenum))

;; wrap values
(define GL_CLAMP_TO_EDGE (foreign-value "GL_CLAMP_TO_EDGE" GLenum))
(define GL_CLAMP_TO_BORDER (foreign-value "GL_CLAMP_TO_BORDER" GLenum))
(define GL_MIRRORED_REPEAT (foreign-value "GL_MIRRORED_REPEAT" GLenum))
(define GL_REPEAT (foreign-value "GL_REPEAT" GLenum))
(define GL_MIRROR_CLAMP_TO_EDGE (foreign-value "GL_MIRROR_CLAMP_TO_EDGE" GLenum))


;; funcs
(define glGenTextures (foreign-lambda void glGenTextures size_t u32vector))
(define glBindTexture (foreign-lambda void glBindTexture GLenum unsigned-int))
(define glTexParameteri (foreign-lambda void glTexParameteri GLenum GLenum int))
(define glTexImage2D
  (foreign-lambda void glTexImage2D
    GLenum int int size_t size_t int GLenum GLenum c-pointer))

)
