;; this will be glew+opengl
(module (egggame glew) *

(import (scheme)
        (chicken base)
        (chicken syntax)
        (chicken module)
        (chicken foreign)
        (srfi-4))

(foreign-declare "#include <GL/glew.h>")

(define-foreign-type GLenum unsigned-int)
(define-foreign-type GLintptr int)
(define-foreign-type GLsizeiptr int)

;; =============================================================================
;; glew stuff
;; =============================================================================

(define GLEW_OK (foreign-value "GLEW_OK" GLenum))
(define glewInit (foreign-lambda GLenum glewInit))

;; =============================================================================
;; capabilities
;; =============================================================================

(define GL_BLEND (foreign-value "GL_BLEND" GLenum))
;(define GL_CLIP_DISTANCE (foreign-value "GL_CLIP_DISTANCE" GLenum))
(define GL_COLOR_LOGIC_OP (foreign-value "GL_COLOR_LOGIC_OP" GLenum))
(define GL_CULL_FACE (foreign-value "GL_CULL_FACE" GLenum))
(define GL_DEBUG_OUTPUT (foreign-value "GL_DEBUG_OUTPUT" GLenum))
(define GL_DEBUG_OUTPUT_SYNCHRONOUS (foreign-value "GL_DEBUG_OUTPUT_SYNCHRONOUS" GLenum))
(define GL_DEPTH_CLAMP (foreign-value "GL_DEPTH_CLAMP" GLenum))
(define GL_DEPTH_TEST (foreign-value "GL_DEPTH_TEST" GLenum))
(define GL_DITHER (foreign-value "GL_DITHER" GLenum))
(define GL_FRAMEBUFFER_SRGB (foreign-value "GL_FRAMEBUFFER_SRGB" GLenum))
(define GL_LINE_SMOOTH (foreign-value "GL_LINE_SMOOTH" GLenum))
(define GL_MULTISAMPLE (foreign-value "GL_MULTISAMPLE" GLenum))
(define GL_POLYGON_OFFSET_FILL (foreign-value "GL_POLYGON_OFFSET_FILL" GLenum))
(define GL_POLYGON_OFFSET_LINE (foreign-value "GL_POLYGON_OFFSET_LINE" GLenum))
(define GL_POLYGON_OFFSET_POINT (foreign-value "GL_POLYGON_OFFSET_POINT" GLenum))
(define GL_POLYGON_SMOOTH (foreign-value "GL_POLYGON_SMOOTH" GLenum))
(define GL_PRIMITIVE_RESTART_FIXED_INDEX (foreign-value "GL_PRIMITIVE_RESTART_FIXED_INDEX" GLenum))
(define GL_PRIMITIVE_RESTART (foreign-value "GL_PRIMITIVE_RESTART" GLenum))
(define GL_PROGRAM_POINT_SIZE (foreign-value "GL_PROGRAM_POINT_SIZE" GLenum))
(define GL_RASTERIZER_DISCARD (foreign-value "GL_RASTERIZER_DISCARD" GLenum))
(define GL_SAMPLE_ALPHA_TO_COVERAGE (foreign-value "GL_SAMPLE_ALPHA_TO_COVERAGE" GLenum))
(define GL_SAMPLE_ALPHA_TO_ONE (foreign-value "GL_SAMPLE_ALPHA_TO_ONE" GLenum))
(define GL_SAMPLE_COVERAGE (foreign-value "GL_SAMPLE_COVERAGE" GLenum))
(define GL_SAMPLE_MASK (foreign-value "GL_SAMPLE_MASK" GLenum))
(define GL_SAMPLE_SHADING (foreign-value "GL_SAMPLE_SHADING" GLenum))
(define GL_SCISSOR_TEST (foreign-value "GL_SCISSOR_TEST" GLenum))
(define GL_STENCIL_TEST (foreign-value "GL_STENCIL_TEST" GLenum))
(define GL_TEXTURE_CUBE_MAP_SEAMLESS (foreign-value "GL_TEXTURE_CUBE_MAP_SEAMLESS" GLenum))

(define glEnable (foreign-lambda void glEnable GLenum))
(define glDisable (foreign-lambda void glDisable GLenum))

(define GL_ACTIVE_TEXTURE (foreign-value "GL_ACTIVE_TEXTURE" GLenum))
(define GL_ALIASED_LINE_WIDTH_RANGE (foreign-value "GL_ALIASED_LINE_WIDTH_RANGE" GLenum))
(define GL_ARRAY_BUFFER_BINDING (foreign-value "GL_ARRAY_BUFFER_BINDING" GLenum))
(define GL_BLEND_COLOR (foreign-value "GL_BLEND_COLOR" GLenum))
(define GL_BLEND_DST_ALPHA (foreign-value "GL_BLEND_DST_ALPHA" GLenum))
(define GL_BLEND_DST_RGB (foreign-value "GL_BLEND_DST_RGB" GLenum))
(define GL_BLEND_EQUATION_ALPHA (foreign-value "GL_BLEND_EQUATION_ALPHA" GLenum))
(define GL_BLEND_EQUATION_RGB (foreign-value "GL_BLEND_EQUATION_RGB" GLenum))
(define GL_BLEND (foreign-value "GL_BLEND" GLenum))
(define GL_BLEND_SRC_ALPHA (foreign-value "GL_BLEND_SRC_ALPHA" GLenum))
(define GL_BLEND_SRC_RGB (foreign-value "GL_BLEND_SRC_RGB" GLenum))
(define GL_COLOR_CLEAR_VALUE (foreign-value "GL_COLOR_CLEAR_VALUE" GLenum))
(define GL_COLOR_LOGIC_OP (foreign-value "GL_COLOR_LOGIC_OP" GLenum))
(define GL_COLOR_WRITEMASK (foreign-value "GL_COLOR_WRITEMASK" GLenum))
(define GL_COMPRESSED_TEXTURE_FORMATS (foreign-value "GL_COMPRESSED_TEXTURE_FORMATS" GLenum))
(define GL_CONTEXT_FLAGS (foreign-value "GL_CONTEXT_FLAGS" GLenum))
(define GL_CULL_FACE (foreign-value "GL_CULL_FACE" GLenum))
(define GL_CULL_FACE_MODE (foreign-value "GL_CULL_FACE_MODE" GLenum))
(define GL_CURRENT_PROGRAM (foreign-value "GL_CURRENT_PROGRAM" GLenum))
(define GL_DEBUG_GROUP_STACK_DEPTH (foreign-value "GL_DEBUG_GROUP_STACK_DEPTH" GLenum))
(define GL_DEPTH_CLEAR_VALUE (foreign-value "GL_DEPTH_CLEAR_VALUE" GLenum))
(define GL_DEPTH_FUNC (foreign-value "GL_DEPTH_FUNC" GLenum))
(define GL_DEPTH_RANGE (foreign-value "GL_DEPTH_RANGE" GLenum))
(define GL_DEPTH_TEST (foreign-value "GL_DEPTH_TEST" GLenum))
(define GL_DEPTH_WRITEMASK (foreign-value "GL_DEPTH_WRITEMASK" GLenum))
(define GL_DISPATCH_INDIRECT_BUFFER_BINDING (foreign-value "GL_DISPATCH_INDIRECT_BUFFER_BINDING" GLenum))
(define GL_DITHER (foreign-value "GL_DITHER" GLenum))
(define GL_DOUBLEBUFFER (foreign-value "GL_DOUBLEBUFFER" GLenum))
(define GL_DRAW_BUFFER (foreign-value "GL_DRAW_BUFFER" GLenum))
(define GL_DRAW_FRAMEBUFFER_BINDING (foreign-value "GL_DRAW_FRAMEBUFFER_BINDING" GLenum))
(define GL_ELEMENT_ARRAY_BUFFER_BINDING (foreign-value "GL_ELEMENT_ARRAY_BUFFER_BINDING" GLenum))
(define GL_FRAGMENT_SHADER_DERIVATIVE_HINT (foreign-value "GL_FRAGMENT_SHADER_DERIVATIVE_HINT" GLenum))
(define GL_IMPLEMENTATION_COLOR_READ_FORMAT (foreign-value "GL_IMPLEMENTATION_COLOR_READ_FORMAT" GLenum))
(define GL_IMPLEMENTATION_COLOR_READ_TYPE (foreign-value "GL_IMPLEMENTATION_COLOR_READ_TYPE" GLenum))
(define GL_LAYER_PROVOKING_VERTEX (foreign-value "GL_LAYER_PROVOKING_VERTEX" GLenum))
(define GL_LINE_SMOOTH (foreign-value "GL_LINE_SMOOTH" GLenum))
(define GL_LINE_SMOOTH_HINT (foreign-value "GL_LINE_SMOOTH_HINT" GLenum))
(define GL_LINE_WIDTH (foreign-value "GL_LINE_WIDTH" GLenum))
(define GL_LOGIC_OP_MODE (foreign-value "GL_LOGIC_OP_MODE" GLenum))
(define GL_MAJOR_VERSION (foreign-value "GL_MAJOR_VERSION" GLenum))
(define GL_MAX_3D_TEXTURE_SIZE (foreign-value "GL_MAX_3D_TEXTURE_SIZE" GLenum))
(define GL_MAX_ARRAY_TEXTURE_LAYERS (foreign-value "GL_MAX_ARRAY_TEXTURE_LAYERS" GLenum))
(define GL_MAX_CLIP_DISTANCES (foreign-value "GL_MAX_CLIP_DISTANCES" GLenum))
(define GL_MAX_COLOR_TEXTURE_SAMPLES (foreign-value "GL_MAX_COLOR_TEXTURE_SAMPLES" GLenum))
(define GL_MAX_COMBINED_ATOMIC_COUNTERS (foreign-value "GL_MAX_COMBINED_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS (foreign-value "GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS (foreign-value "GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS (foreign-value "GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS" GLenum))
(define GL_MAX_COMBINED_UNIFORM_BLOCKS (foreign-value "GL_MAX_COMBINED_UNIFORM_BLOCKS" GLenum))
(define GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS (foreign-value "GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS (foreign-value "GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS" GLenum))
(define GL_MAX_COMPUTE_ATOMIC_COUNTERS (foreign-value "GL_MAX_COMPUTE_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS" GLenum))
(define GL_MAX_COMPUTE_UNIFORM_BLOCKS (foreign-value "GL_MAX_COMPUTE_UNIFORM_BLOCKS" GLenum))
(define GL_MAX_COMPUTE_UNIFORM_COMPONENTS (foreign-value "GL_MAX_COMPUTE_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_COMPUTE_WORK_GROUP_COUNT (foreign-value "GL_MAX_COMPUTE_WORK_GROUP_COUNT" GLenum))
(define GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS (foreign-value "GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS" GLenum))
(define GL_MAX_COMPUTE_WORK_GROUP_SIZE (foreign-value "GL_MAX_COMPUTE_WORK_GROUP_SIZE" GLenum))
(define GL_MAX_CUBE_MAP_TEXTURE_SIZE (foreign-value "GL_MAX_CUBE_MAP_TEXTURE_SIZE" GLenum))
(define GL_MAX_DEBUG_GROUP_STACK_DEPTH (foreign-value "GL_MAX_DEBUG_GROUP_STACK_DEPTH" GLenum))
(define GL_MAX_DEPTH_TEXTURE_SAMPLES (foreign-value "GL_MAX_DEPTH_TEXTURE_SAMPLES" GLenum))
(define GL_MAX_DRAW_BUFFERS (foreign-value "GL_MAX_DRAW_BUFFERS" GLenum))
(define GL_MAX_DUAL_SOURCE_DRAW_BUFFERS (foreign-value "GL_MAX_DUAL_SOURCE_DRAW_BUFFERS" GLenum))
(define GL_MAX_ELEMENT_INDEX (foreign-value "GL_MAX_ELEMENT_INDEX" GLenum))
(define GL_MAX_ELEMENTS_INDICES (foreign-value "GL_MAX_ELEMENTS_INDICES" GLenum))
(define GL_MAX_ELEMENTS_VERTICES (foreign-value "GL_MAX_ELEMENTS_VERTICES" GLenum))
(define GL_MAX_FRAGMENT_ATOMIC_COUNTERS (foreign-value "GL_MAX_FRAGMENT_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_FRAGMENT_INPUT_COMPONENTS (foreign-value "GL_MAX_FRAGMENT_INPUT_COMPONENTS" GLenum))
(define GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_FRAGMENT_UNIFORM_BLOCKS (foreign-value "GL_MAX_FRAGMENT_UNIFORM_BLOCKS" GLenum))
(define GL_MAX_FRAGMENT_UNIFORM_COMPONENTS (foreign-value "GL_MAX_FRAGMENT_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_FRAGMENT_UNIFORM_VECTORS (foreign-value "GL_MAX_FRAGMENT_UNIFORM_VECTORS" GLenum))
(define GL_MAX_FRAMEBUFFER_HEIGHT (foreign-value "GL_MAX_FRAMEBUFFER_HEIGHT" GLenum))
(define GL_MAX_FRAMEBUFFER_LAYERS (foreign-value "GL_MAX_FRAMEBUFFER_LAYERS" GLenum))
(define GL_MAX_FRAMEBUFFER_SAMPLES (foreign-value "GL_MAX_FRAMEBUFFER_SAMPLES" GLenum))
(define GL_MAX_FRAMEBUFFER_WIDTH (foreign-value "GL_MAX_FRAMEBUFFER_WIDTH" GLenum))
(define GL_MAX_GEOMETRY_ATOMIC_COUNTERS (foreign-value "GL_MAX_GEOMETRY_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_GEOMETRY_INPUT_COMPONENTS (foreign-value "GL_MAX_GEOMETRY_INPUT_COMPONENTS" GLenum))
(define GL_MAX_GEOMETRY_OUTPUT_COMPONENTS (foreign-value "GL_MAX_GEOMETRY_OUTPUT_COMPONENTS" GLenum))
(define GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS" GLenum))
(define GL_MAX_GEOMETRY_UNIFORM_BLOCKS (foreign-value "GL_MAX_GEOMETRY_UNIFORM_BLOCKS" GLenum))
(define GL_MAX_GEOMETRY_UNIFORM_COMPONENTS (foreign-value "GL_MAX_GEOMETRY_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_INTEGER_SAMPLES (foreign-value "GL_MAX_INTEGER_SAMPLES" GLenum))
(define GL_MAX_LABEL_LENGTH (foreign-value "GL_MAX_LABEL_LENGTH" GLenum))
(define GL_MAX_PROGRAM_TEXEL_OFFSET (foreign-value "GL_MAX_PROGRAM_TEXEL_OFFSET" GLenum))
(define GL_MAX_RECTANGLE_TEXTURE_SIZE (foreign-value "GL_MAX_RECTANGLE_TEXTURE_SIZE" GLenum))
(define GL_MAX_RENDERBUFFER_SIZE (foreign-value "GL_MAX_RENDERBUFFER_SIZE" GLenum))
(define GL_MAX_SAMPLE_MASK_WORDS (foreign-value "GL_MAX_SAMPLE_MASK_WORDS" GLenum))
(define GL_MAX_SERVER_WAIT_TIMEOUT (foreign-value "GL_MAX_SERVER_WAIT_TIMEOUT" GLenum))
(define GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS (foreign-value "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" GLenum))
(define GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS (foreign-value "GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS (foreign-value "GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_TEXTURE_BUFFER_SIZE (foreign-value "GL_MAX_TEXTURE_BUFFER_SIZE" GLenum))
(define GL_MAX_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_TEXTURE_IMAGE_UNITS" GLenum))
(define GL_MAX_TEXTURE_LOD_BIAS (foreign-value "GL_MAX_TEXTURE_LOD_BIAS" GLenum))
(define GL_MAX_TEXTURE_SIZE (foreign-value "GL_MAX_TEXTURE_SIZE" GLenum))
(define GL_MAX_UNIFORM_BLOCK_SIZE (foreign-value "GL_MAX_UNIFORM_BLOCK_SIZE" GLenum))
(define GL_MAX_UNIFORM_BUFFER_BINDINGS (foreign-value "GL_MAX_UNIFORM_BUFFER_BINDINGS" GLenum))
(define GL_MAX_UNIFORM_LOCATIONS (foreign-value "GL_MAX_UNIFORM_LOCATIONS" GLenum))
(define GL_MAX_VARYING_COMPONENTS (foreign-value "GL_MAX_VARYING_COMPONENTS" GLenum))
(define GL_MAX_VARYING_FLOATS (foreign-value "GL_MAX_VARYING_FLOATS" GLenum))
(define GL_MAX_VARYING_VECTORS (foreign-value "GL_MAX_VARYING_VECTORS" GLenum))
(define GL_MAX_VERTEX_ATOMIC_COUNTERS (foreign-value "GL_MAX_VERTEX_ATOMIC_COUNTERS" GLenum))
(define GL_MAX_VERTEX_ATTRIB_BINDINGS (foreign-value "GL_MAX_VERTEX_ATTRIB_BINDINGS" GLenum))
(define GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET (foreign-value "GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET" GLenum))
(define GL_MAX_VERTEX_ATTRIBS (foreign-value "GL_MAX_VERTEX_ATTRIBS" GLenum))
(define GL_MAX_VERTEX_OUTPUT_COMPONENTS (foreign-value "GL_MAX_VERTEX_OUTPUT_COMPONENTS" GLenum))
(define GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS (foreign-value "GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS" GLenum))
(define GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS" GLenum))
(define GL_MAX_VERTEX_UNIFORM_BLOCKS (foreign-value "GL_MAX_VERTEX_UNIFORM_BLOCKS" GLenum))
(define GL_MAX_VERTEX_UNIFORM_COMPONENTS (foreign-value "GL_MAX_VERTEX_UNIFORM_COMPONENTS" GLenum))
(define GL_MAX_VERTEX_UNIFORM_VECTORS (foreign-value "GL_MAX_VERTEX_UNIFORM_VECTORS" GLenum))
(define GL_MAX_VIEWPORT_DIMS (foreign-value "GL_MAX_VIEWPORT_DIMS" GLenum))
(define GL_MAX_VIEWPORTS (foreign-value "GL_MAX_VIEWPORTS" GLenum))
(define GL_MIN_MAP_BUFFER_ALIGNMENT (foreign-value "GL_MIN_MAP_BUFFER_ALIGNMENT" GLenum))
(define GL_MINOR_VERSION (foreign-value "GL_MINOR_VERSION" GLenum))
(define GL_MIN_PROGRAM_TEXEL_OFFSET (foreign-value "GL_MIN_PROGRAM_TEXEL_OFFSET" GLenum))
(define GL_NUM_COMPRESSED_TEXTURE_FORMATS (foreign-value "GL_NUM_COMPRESSED_TEXTURE_FORMATS" GLenum))
(define GL_NUM_EXTENSIONS (foreign-value "GL_NUM_EXTENSIONS" GLenum))
(define GL_NUM_PROGRAM_BINARY_FORMATS (foreign-value "GL_NUM_PROGRAM_BINARY_FORMATS" GLenum))
(define GL_NUM_SHADER_BINARY_FORMATS (foreign-value "GL_NUM_SHADER_BINARY_FORMATS" GLenum))
(define GL_PACK_ALIGNMENT (foreign-value "GL_PACK_ALIGNMENT" GLenum))
(define GL_PACK_IMAGE_HEIGHT (foreign-value "GL_PACK_IMAGE_HEIGHT" GLenum))
(define GL_PACK_LSB_FIRST (foreign-value "GL_PACK_LSB_FIRST" GLenum))
(define GL_PACK_ROW_LENGTH (foreign-value "GL_PACK_ROW_LENGTH" GLenum))
(define GL_PACK_SKIP_IMAGES (foreign-value "GL_PACK_SKIP_IMAGES" GLenum))
(define GL_PACK_SKIP_PIXELS (foreign-value "GL_PACK_SKIP_PIXELS" GLenum))
(define GL_PACK_SKIP_ROWS (foreign-value "GL_PACK_SKIP_ROWS" GLenum))
(define GL_PACK_SWAP_BYTES (foreign-value "GL_PACK_SWAP_BYTES" GLenum))
(define GL_PIXEL_PACK_BUFFER_BINDING (foreign-value "GL_PIXEL_PACK_BUFFER_BINDING" GLenum))
(define GL_PIXEL_UNPACK_BUFFER_BINDING (foreign-value "GL_PIXEL_UNPACK_BUFFER_BINDING" GLenum))
(define GL_POINT_FADE_THRESHOLD_SIZE (foreign-value "GL_POINT_FADE_THRESHOLD_SIZE" GLenum))
(define GL_POINT_SIZE (foreign-value "GL_POINT_SIZE" GLenum))
(define GL_POINT_SIZE_GRANULARITY (foreign-value "GL_POINT_SIZE_GRANULARITY" GLenum))
(define GL_POINT_SIZE_RANGE (foreign-value "GL_POINT_SIZE_RANGE" GLenum))
(define GL_POLYGON_OFFSET_FACTOR (foreign-value "GL_POLYGON_OFFSET_FACTOR" GLenum))
(define GL_POLYGON_OFFSET_FILL (foreign-value "GL_POLYGON_OFFSET_FILL" GLenum))
(define GL_POLYGON_OFFSET_LINE (foreign-value "GL_POLYGON_OFFSET_LINE" GLenum))
(define GL_POLYGON_OFFSET_POINT (foreign-value "GL_POLYGON_OFFSET_POINT" GLenum))
(define GL_POLYGON_OFFSET_UNITS (foreign-value "GL_POLYGON_OFFSET_UNITS" GLenum))
(define GL_POLYGON_SMOOTH (foreign-value "GL_POLYGON_SMOOTH" GLenum))
(define GL_POLYGON_SMOOTH_HINT (foreign-value "GL_POLYGON_SMOOTH_HINT" GLenum))
(define GL_PRIMITIVE_RESTART_INDEX (foreign-value "GL_PRIMITIVE_RESTART_INDEX" GLenum))
(define GL_PROGRAM_BINARY_FORMATS (foreign-value "GL_PROGRAM_BINARY_FORMATS" GLenum))
(define GL_PROGRAM_PIPELINE_BINDING (foreign-value "GL_PROGRAM_PIPELINE_BINDING" GLenum))
(define GL_PROGRAM_POINT_SIZE (foreign-value "GL_PROGRAM_POINT_SIZE" GLenum))
(define GL_PROVOKING_VERTEX (foreign-value "GL_PROVOKING_VERTEX" GLenum))
(define GL_READ_BUFFER (foreign-value "GL_READ_BUFFER" GLenum))
(define GL_READ_FRAMEBUFFER_BINDING (foreign-value "GL_READ_FRAMEBUFFER_BINDING" GLenum))
(define GL_RENDERBUFFER_BINDING (foreign-value "GL_RENDERBUFFER_BINDING" GLenum))
(define GL_SAMPLE_BUFFERS (foreign-value "GL_SAMPLE_BUFFERS" GLenum))
(define GL_SAMPLE_COVERAGE_INVERT (foreign-value "GL_SAMPLE_COVERAGE_INVERT" GLenum))
(define GL_SAMPLE_COVERAGE_VALUE (foreign-value "GL_SAMPLE_COVERAGE_VALUE" GLenum))
(define GL_SAMPLE_MASK_VALUE (foreign-value "GL_SAMPLE_MASK_VALUE" GLenum))
(define GL_SAMPLER_BINDING (foreign-value "GL_SAMPLER_BINDING" GLenum))
(define GL_SAMPLES (foreign-value "GL_SAMPLES" GLenum))
(define GL_SCISSOR_BOX (foreign-value "GL_SCISSOR_BOX" GLenum))
(define GL_SCISSOR_TEST (foreign-value "GL_SCISSOR_TEST" GLenum))
(define GL_SHADER_COMPILER (foreign-value "GL_SHADER_COMPILER" GLenum))
(define GL_SHADER_STORAGE_BUFFER_BINDING (foreign-value "GL_SHADER_STORAGE_BUFFER_BINDING" GLenum))
(define GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT (foreign-value "GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT" GLenum))
(define GL_SHADER_STORAGE_BUFFER_SIZE (foreign-value "GL_SHADER_STORAGE_BUFFER_SIZE" GLenum))
(define GL_SHADER_STORAGE_BUFFER_START (foreign-value "GL_SHADER_STORAGE_BUFFER_START" GLenum))
(define GL_SMOOTH_LINE_WIDTH_GRANULARITY (foreign-value "GL_SMOOTH_LINE_WIDTH_GRANULARITY" GLenum))
(define GL_SMOOTH_LINE_WIDTH_RANGE (foreign-value "GL_SMOOTH_LINE_WIDTH_RANGE" GLenum))
(define GL_STENCIL_BACK_FAIL (foreign-value "GL_STENCIL_BACK_FAIL" GLenum))
(define GL_STENCIL_BACK_FUNC (foreign-value "GL_STENCIL_BACK_FUNC" GLenum))
(define GL_STENCIL_BACK_PASS_DEPTH_FAIL (foreign-value "GL_STENCIL_BACK_PASS_DEPTH_FAIL" GLenum))
(define GL_STENCIL_BACK_PASS_DEPTH_PASS (foreign-value "GL_STENCIL_BACK_PASS_DEPTH_PASS" GLenum))
(define GL_STENCIL_BACK_REF (foreign-value "GL_STENCIL_BACK_REF" GLenum))
(define GL_STENCIL_BACK_VALUE_MASK (foreign-value "GL_STENCIL_BACK_VALUE_MASK" GLenum))
(define GL_STENCIL_BACK_WRITEMASK (foreign-value "GL_STENCIL_BACK_WRITEMASK" GLenum))
(define GL_STENCIL_CLEAR_VALUE (foreign-value "GL_STENCIL_CLEAR_VALUE" GLenum))
(define GL_STENCIL_FAIL (foreign-value "GL_STENCIL_FAIL" GLenum))
(define GL_STENCIL_FUNC (foreign-value "GL_STENCIL_FUNC" GLenum))
(define GL_STENCIL_PASS_DEPTH_FAIL (foreign-value "GL_STENCIL_PASS_DEPTH_FAIL" GLenum))
(define GL_STENCIL_PASS_DEPTH_PASS (foreign-value "GL_STENCIL_PASS_DEPTH_PASS" GLenum))
(define GL_STENCIL_REF (foreign-value "GL_STENCIL_REF" GLenum))
(define GL_STENCIL_TEST (foreign-value "GL_STENCIL_TEST" GLenum))
(define GL_STENCIL_VALUE_MASK (foreign-value "GL_STENCIL_VALUE_MASK" GLenum))
(define GL_STENCIL_WRITEMASK (foreign-value "GL_STENCIL_WRITEMASK" GLenum))
(define GL_STEREO (foreign-value "GL_STEREO" GLenum))
(define GL_SUBPIXEL_BITS (foreign-value "GL_SUBPIXEL_BITS" GLenum))
(define GL_TEXTURE_BINDING_1D_ARRAY (foreign-value "GL_TEXTURE_BINDING_1D_ARRAY" GLenum))
(define GL_TEXTURE_BINDING_1D (foreign-value "GL_TEXTURE_BINDING_1D" GLenum))
(define GL_TEXTURE_BINDING_2D_ARRAY (foreign-value "GL_TEXTURE_BINDING_2D_ARRAY" GLenum))
(define GL_TEXTURE_BINDING_2D (foreign-value "GL_TEXTURE_BINDING_2D" GLenum))
(define GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY (foreign-value "GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY" GLenum))
(define GL_TEXTURE_BINDING_2D_MULTISAMPLE (foreign-value "GL_TEXTURE_BINDING_2D_MULTISAMPLE" GLenum))
(define GL_TEXTURE_BINDING_3D (foreign-value "GL_TEXTURE_BINDING_3D" GLenum))
(define GL_TEXTURE_BINDING_BUFFER (foreign-value "GL_TEXTURE_BINDING_BUFFER" GLenum))
(define GL_TEXTURE_BINDING_CUBE_MAP (foreign-value "GL_TEXTURE_BINDING_CUBE_MAP" GLenum))
(define GL_TEXTURE_BINDING_RECTANGLE (foreign-value "GL_TEXTURE_BINDING_RECTANGLE" GLenum))
(define GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT (foreign-value "GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT" GLenum))
(define GL_TEXTURE_COMPRESSION_HINT (foreign-value "GL_TEXTURE_COMPRESSION_HINT" GLenum))
(define GL_TIMESTAMP (foreign-value "GL_TIMESTAMP" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER_BINDING (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER_BINDING" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER_SIZE (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER_SIZE" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER_START (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER_START" GLenum))
(define GL_UNIFORM_BUFFER_BINDING (foreign-value "GL_UNIFORM_BUFFER_BINDING" GLenum))
(define GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT (foreign-value "GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT" GLenum))
(define GL_UNIFORM_BUFFER_SIZE (foreign-value "GL_UNIFORM_BUFFER_SIZE" GLenum))
(define GL_UNIFORM_BUFFER_START (foreign-value "GL_UNIFORM_BUFFER_START" GLenum))
(define GL_UNPACK_ALIGNMENT (foreign-value "GL_UNPACK_ALIGNMENT" GLenum))
(define GL_UNPACK_IMAGE_HEIGHT (foreign-value "GL_UNPACK_IMAGE_HEIGHT" GLenum))
(define GL_UNPACK_LSB_FIRST (foreign-value "GL_UNPACK_LSB_FIRST" GLenum))
(define GL_UNPACK_ROW_LENGTH (foreign-value "GL_UNPACK_ROW_LENGTH" GLenum))
(define GL_UNPACK_SKIP_IMAGES (foreign-value "GL_UNPACK_SKIP_IMAGES" GLenum))
(define GL_UNPACK_SKIP_PIXELS (foreign-value "GL_UNPACK_SKIP_PIXELS" GLenum))
(define GL_UNPACK_SKIP_ROWS (foreign-value "GL_UNPACK_SKIP_ROWS" GLenum))
(define GL_UNPACK_SWAP_BYTES (foreign-value "GL_UNPACK_SWAP_BYTES" GLenum))
(define GL_VERTEX_ARRAY_BINDING (foreign-value "GL_VERTEX_ARRAY_BINDING" GLenum))
(define GL_VERTEX_BINDING_BUFFER (foreign-value "GL_VERTEX_BINDING_BUFFER" GLenum))
(define GL_VERTEX_BINDING_DIVISOR (foreign-value "GL_VERTEX_BINDING_DIVISOR" GLenum))
(define GL_VERTEX_BINDING_OFFSET (foreign-value "GL_VERTEX_BINDING_OFFSET" GLenum))
(define GL_VERTEX_BINDING_STRIDE (foreign-value "GL_VERTEX_BINDING_STRIDE" GLenum))
(define GL_VIEWPORT_BOUNDS_RANGE (foreign-value "GL_VIEWPORT_BOUNDS_RANGE" GLenum))
(define GL_VIEWPORT (foreign-value "GL_VIEWPORT" GLenum))
(define GL_VIEWPORT_INDEX_PROVOKING_VERTEX (foreign-value "GL_VIEWPORT_INDEX_PROVOKING_VERTEX" GLenum))
(define GL_VIEWPORT_SUBPIXEL_BITS (foreign-value "GL_VIEWPORT_SUBPIXEL_BITS" GLenum))

(define glGetIntegerv (foreign-lambda void glGetIntegerv GLenum s32vector))

;; =============================================================================
;; errors
;; =============================================================================

(define GL_NO_ERROR (foreign-value "GL_NO_ERROR" GLenum))
(define GL_INVALID_ENUM (foreign-value "GL_INVALID_ENUM" GLenum))
(define GL_INVALID_VALUE (foreign-value "GL_INVALID_VALUE" GLenum))
(define GL_INVALID_OPERATION (foreign-value "GL_INVALID_OPERATION" GLenum))
(define GL_INVALID_FRAMEBUFFER_OPERATION (foreign-value "GL_INVALID_FRAMEBUFFER_OPERATION" GLenum))
(define GL_OUT_OF_MEMORY (foreign-value "GL_OUT_OF_MEMORY" GLenum))
(define GL_STACK_UNDERFLOW (foreign-value "GL_STACK_UNDERFLOW" GLenum))
(define GL_STACK_OVERFLOW (foreign-value "GL_STACK_OVERFLOW" GLenum))
(define GL_FALSE (foreign-value "GL_FALSE" GLenum))

(define glGetError (foreign-lambda GLenum glGetError))
(define gluErrorString (foreign-lambda c-string gluErrorString GLenum))

;; =============================================================================
;; buffers
;; =============================================================================

;; sizes I guess
(define sizeof-GLfloat (foreign-value "sizeof(GLfloat)" size_t))
(define sizeof-GLint (foreign-value "sizeof(GLint)" size_t))

;; buffer types
(define GL_ARRAY_BUFFER (foreign-value "GL_ARRAY_BUFFER" GLenum))
(define GL_ATOMIC_COUNTER_BUFFER (foreign-value "GL_ATOMIC_COUNTER_BUFFER" GLenum))
(define GL_COPY_READ_BUFFER (foreign-value "GL_COPY_READ_BUFFER" GLenum))
(define GL_COPY_WRITE_BUFFER (foreign-value "GL_COPY_WRITE_BUFFER" GLenum))
(define GL_DISPATCH_INDIRECT_BUFFER (foreign-value "GL_DISPATCH_INDIRECT_BUFFER" GLenum))
(define GL_DRAW_INDIRECT_BUFFER (foreign-value "GL_DRAW_INDIRECT_BUFFER" GLenum))
(define GL_ELEMENT_ARRAY_BUFFER (foreign-value "GL_ELEMENT_ARRAY_BUFFER" GLenum))
(define GL_PIXEL_PACK_BUFFER (foreign-value "GL_PIXEL_PACK_BUFFER" GLenum))
(define GL_PIXEL_UNPACK_BUFFER (foreign-value "GL_PIXEL_UNPACK_BUFFER" GLenum))
(define GL_QUERY_BUFFER (foreign-value "GL_QUERY_BUFFER" GLenum))
(define GL_SHADER_STORAGE_BUFFER (foreign-value "GL_SHADER_STORAGE_BUFFER" GLenum))
(define GL_TEXTURE_BUFFER (foreign-value "GL_TEXTURE_BUFFER" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER" GLenum))
(define GL_UNIFORM_BUFFER (foreign-value "GL_UNIFORM_BUFFER" GLenum))

;; buffer usages
(define GL_STREAM_DRAW (foreign-value "GL_STREAM_DRAW" GLenum))
(define GL_STREAM_READ (foreign-value "GL_STREAM_READ" GLenum))
(define GL_STREAM_COPY (foreign-value "GL_STREAM_COPY" GLenum))
(define GL_STATIC_DRAW (foreign-value "GL_STATIC_DRAW" GLenum))
(define GL_STATIC_READ (foreign-value "GL_STATIC_READ" GLenum))
(define GL_STATIC_COPY (foreign-value "GL_STATIC_COPY" GLenum))
(define GL_DYNAMIC_DRAW (foreign-value "GL_DYNAMIC_DRAW" GLenum))
(define GL_DYNAMIC_READ (foreign-value "GL_DYNAMIC_READ" GLenum))
(define GL_DYNAMIC_COPY (foreign-value "GL_DYNAMIC_COPY" GLenum))

;; funcs
(define glGenBuffers (foreign-lambda void glGenBuffers size_t u32vector))
(define glBindBuffer (foreign-lambda void glBindBuffer GLenum unsigned-int))
(define glBufferData (foreign-lambda void glBufferData GLenum unsigned-integer64 blob GLenum))
(define glBufferSubData (foreign-lambda void glBufferSubData GLenum GLintptr GLsizeiptr blob))
(define glDeleteBuffers (foreign-lambda void glDeleteBuffers size_t u32vector))

(define glVertexAttribPointer (foreign-lambda void glVertexAttribPointer unsigned-int int GLenum bool size_t c-pointer))
(define glVertexAttribIPointer (foreign-lambda void glVertexAttribIPointer unsigned-int int GLenum size_t c-pointer))
(define glEnableVertexAttribArray (foreign-lambda void glEnableVertexAttribArray unsigned-int))
(define glDisableVertexAttribArray (foreign-lambda void glDisableVertexAttribArray unsigned-int))

;; =============================================================================
;; textures
;; =============================================================================

;; targets
(define GL_TEXTURE_1D (foreign-value "GL_TEXTURE_1D" GLenum))
(define GL_TEXTURE_1D_ARRAY (foreign-value "GL_TEXTURE_1D_ARRAY" GLenum))
(define GL_TEXTURE_2D (foreign-value "GL_TEXTURE_2D" GLenum))
(define GL_TEXTURE_2D_ARRAY (foreign-value "GL_TEXTURE_2D_ARRAY" GLenum))
(define GL_TEXTURE_2D_MULTISAMPLE (foreign-value "GL_TEXTURE_2D_MULTISAMPLE" GLenum))
(define GL_TEXTURE_2D_MULTISAMPLE_ARRAY (foreign-value "GL_TEXTURE_2D_MULTISAMPLE_ARRAY" GLenum))
(define GL_TEXTURE_3D (foreign-value "GL_TEXTURE_3D" GLenum))
(define GL_TEXTURE_CUBE_MAP (foreign-value "GL_TEXTURE_CUBE_MAP" GLenum))
(define GL_TEXTURE_CUBE_MAP_ARRAY (foreign-value "GL_TEXTURE_CUBE_MAP_ARRAY" GLenum))
(define GL_TEXTURE_RECTANGLE (foreign-value "GL_TEXTURE_RECTANGLE" GLenum))

;; pnames
(define GL_DEPTH_STENCIL_TEXTURE_MODE (foreign-value "GL_DEPTH_STENCIL_TEXTURE_MODE" GLenum))
(define GL_TEXTURE_BASE_LEVEL (foreign-value "GL_TEXTURE_BASE_LEVEL" GLenum))
(define GL_TEXTURE_COMPARE_FUNC (foreign-value "GL_TEXTURE_COMPARE_FUNC" GLenum))
(define GL_TEXTURE_COMPARE_MODE (foreign-value "GL_TEXTURE_COMPARE_MODE" GLenum))
(define GL_TEXTURE_LOD_BIAS (foreign-value "GL_TEXTURE_LOD_BIAS" GLenum))
(define GL_TEXTURE_MIN_FILTER (foreign-value "GL_TEXTURE_MIN_FILTER" GLenum))
(define GL_TEXTURE_MAG_FILTER (foreign-value "GL_TEXTURE_MAG_FILTER" GLenum))
(define GL_TEXTURE_MIN_LOD (foreign-value "GL_TEXTURE_MIN_LOD" GLenum))
(define GL_TEXTURE_MAX_LOD (foreign-value "GL_TEXTURE_MAX_LOD" GLenum))
(define GL_TEXTURE_MAX_LEVEL (foreign-value "GL_TEXTURE_MAX_LEVEL" GLenum))
(define GL_TEXTURE_SWIZZLE_R (foreign-value "GL_TEXTURE_SWIZZLE_R" GLenum))
(define GL_TEXTURE_SWIZZLE_G (foreign-value "GL_TEXTURE_SWIZZLE_G" GLenum))
(define GL_TEXTURE_SWIZZLE_B (foreign-value "GL_TEXTURE_SWIZZLE_B" GLenum))
(define GL_TEXTURE_SWIZZLE_A (foreign-value "GL_TEXTURE_SWIZZLE_A" GLenum))
(define GL_TEXTURE_WRAP_S (foreign-value "GL_TEXTURE_WRAP_S" GLenum))
(define GL_TEXTURE_WRAP_T (foreign-value "GL_TEXTURE_WRAP_T" GLenum))
(define GL_TEXTURE_WRAP_R (foreign-value "GL_TEXTURE_WRAP_R" GLenum))

(define GL_TEXTURE0 (foreign-value "GL_TEXTURE0" GLenum))
(define GL_TEXTURE1 (foreign-value "GL_TEXTURE1" GLenum))
(define GL_TEXTURE2 (foreign-value "GL_TEXTURE2" GLenum))
(define GL_TEXTURE3 (foreign-value "GL_TEXTURE3" GLenum))
(define GL_TEXTURE4 (foreign-value "GL_TEXTURE4" GLenum))
(define GL_TEXTURE5 (foreign-value "GL_TEXTURE5" GLenum))
(define GL_TEXTURE6 (foreign-value "GL_TEXTURE6" GLenum))
(define GL_TEXTURE7 (foreign-value "GL_TEXTURE7" GLenum))
(define GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS (foreign-value "GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS" GLenum))

;; internalFormats
(define GL_DEPTH_COMPONENT (foreign-value "GL_DEPTH_COMPONENT" GLenum))
(define GL_DEPTH_STENCIL (foreign-value "GL_DEPTH_STENCIL" GLenum))
(define GL_RED (foreign-value "GL_RED" GLenum))
(define GL_RG (foreign-value "GL_RG" GLenum))
(define GL_RGB (foreign-value "GL_RGB" GLenum))
(define GL_RGBA (foreign-value "GL_RGBA" GLenum))
(define GL_R8 (foreign-value "GL_R8" GLenum))
(define GL_R8_SNORM (foreign-value "GL_R8_SNORM" GLenum))
(define GL_R16 (foreign-value "GL_R16" GLenum))
(define GL_R16_SNORM (foreign-value "GL_R16_SNORM" GLenum))
(define GL_RG8 (foreign-value "GL_RG8" GLenum))
(define GL_RG8_SNORM (foreign-value "GL_RG8_SNORM" GLenum))
(define GL_RG16 (foreign-value "GL_RG16" GLenum))
(define GL_RG16_SNORM (foreign-value "GL_RG16_SNORM" GLenum))
(define GL_R3_G3_B2 (foreign-value "GL_R3_G3_B2" GLenum))
(define GL_RGB4 (foreign-value "GL_RGB4" GLenum))
(define GL_RGB5 (foreign-value "GL_RGB5" GLenum))
(define GL_RGB8 (foreign-value "GL_RGB8" GLenum))
(define GL_RGB8_SNORM (foreign-value "GL_RGB8_SNORM" GLenum))
(define GL_RGB10 (foreign-value "GL_RGB10" GLenum))
(define GL_RGB12 (foreign-value "GL_RGB12" GLenum))
(define GL_RGB16_SNORM (foreign-value "GL_RGB16_SNORM" GLenum))
(define GL_RGBA2 (foreign-value "GL_RGBA2" GLenum))
(define GL_RGBA4 (foreign-value "GL_RGBA4" GLenum))
(define GL_RGB5_A1 (foreign-value "GL_RGB5_A1" GLenum))
(define GL_RGBA8 (foreign-value "GL_RGBA8" GLenum))
(define GL_RGBA8_SNORM (foreign-value "GL_RGBA8_SNORM" GLenum))
(define GL_RGB10_A2 (foreign-value "GL_RGB10_A2" GLenum))
(define GL_RGB10_A2UI (foreign-value "GL_RGB10_A2UI" GLenum))
(define GL_RGBA12 (foreign-value "GL_RGBA12" GLenum))
(define GL_RGBA16 (foreign-value "GL_RGBA16" GLenum))
(define GL_SRGB8 (foreign-value "GL_SRGB8" GLenum))
(define GL_SRGB8_ALPHA8 (foreign-value "GL_SRGB8_ALPHA8" GLenum))
(define GL_R16F (foreign-value "GL_R16F" GLenum))
(define GL_RG16F (foreign-value "GL_RG16F" GLenum))
(define GL_RGB16F (foreign-value "GL_RGB16F" GLenum))
(define GL_RGBA16F (foreign-value "GL_RGBA16F" GLenum))
(define GL_R32F (foreign-value "GL_R32F" GLenum))
(define GL_RG32F (foreign-value "GL_RG32F" GLenum))
(define GL_RGB32F (foreign-value "GL_RGB32F" GLenum))
(define GL_RGBA32F (foreign-value "GL_RGBA32F" GLenum))
(define GL_R11F_G11F_B10F (foreign-value "GL_R11F_G11F_B10F" GLenum))
(define GL_RGB9_E5 (foreign-value "GL_RGB9_E5" GLenum))
(define GL_R8I (foreign-value "GL_R8I" GLenum))
(define GL_R8UI (foreign-value "GL_R8UI" GLenum))
(define GL_R16I (foreign-value "GL_R16I" GLenum))
(define GL_R16UI (foreign-value "GL_R16UI" GLenum))
(define GL_R32I (foreign-value "GL_R32I" GLenum))
(define GL_R32UI (foreign-value "GL_R32UI" GLenum))
(define GL_RG8I (foreign-value "GL_RG8I" GLenum))
(define GL_RG8UI (foreign-value "GL_RG8UI" GLenum))
(define GL_RG16I (foreign-value "GL_RG16I" GLenum))
(define GL_RG16UI (foreign-value "GL_RG16UI" GLenum))
(define GL_RG32I (foreign-value "GL_RG32I" GLenum))
(define GL_RG32UI (foreign-value "GL_RG32UI" GLenum))
(define GL_RGB8I (foreign-value "GL_RGB8I" GLenum))
(define GL_RGB8UI (foreign-value "GL_RGB8UI" GLenum))
(define GL_RGB16I (foreign-value "GL_RGB16I" GLenum))
(define GL_RGB16UI (foreign-value "GL_RGB16UI" GLenum))
(define GL_RGB32I (foreign-value "GL_RGB32I" GLenum))
(define GL_RGB32UI (foreign-value "GL_RGB32UI" GLenum))
(define GL_RGBA8I (foreign-value "GL_RGBA8I" GLenum))
(define GL_RGBA8UI (foreign-value "GL_RGBA8UI" GLenum))
(define GL_RGBA16I (foreign-value "GL_RGBA16I" GLenum))
(define GL_RGBA16UI (foreign-value "GL_RGBA16UI" GLenum))
(define GL_RGBA32I (foreign-value "GL_RGBA32I" GLenum))
(define GL_RGBA32UI (foreign-value "GL_RGBA32UI" GLenum))
(define GL_COMPRESSED_RED (foreign-value "GL_COMPRESSED_RED" GLenum))
(define GL_COMPRESSED_RG (foreign-value "GL_COMPRESSED_RG" GLenum))
(define GL_COMPRESSED_RGB (foreign-value "GL_COMPRESSED_RGB" GLenum))
(define GL_COMPRESSED_RGBA (foreign-value "GL_COMPRESSED_RGBA" GLenum))
(define GL_COMPRESSED_SRGB (foreign-value "GL_COMPRESSED_SRGB" GLenum))
(define GL_COMPRESSED_SRGB_ALPHA (foreign-value "GL_COMPRESSED_SRGB_ALPHA" GLenum))
(define GL_COMPRESSED_RED_RGTC1 (foreign-value "GL_COMPRESSED_RED_RGTC1" GLenum))
(define GL_COMPRESSED_SIGNED_RED_RGTC1 (foreign-value "GL_COMPRESSED_SIGNED_RED_RGTC1" GLenum))
(define GL_COMPRESSED_RG_RGTC2 (foreign-value "GL_COMPRESSED_RG_RGTC2" GLenum))
(define GL_COMPRESSED_SIGNED_RG_RGTC2 (foreign-value "GL_COMPRESSED_SIGNED_RG_RGTC2" GLenum))
(define GL_COMPRESSED_RGBA_BPTC_UNORM (foreign-value "GL_COMPRESSED_RGBA_BPTC_UNORM" GLenum))
(define GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM (foreign-value "GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM" GLenum))
(define GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT (foreign-value "GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT" GLenum))
(define GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT (foreign-value "GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT" GLenum))

;; formats
(define GL_RED (foreign-value "GL_RED" GLenum))
(define GL_RG (foreign-value "GL_RG" GLenum))
(define GL_RGB (foreign-value "GL_RGB" GLenum))
(define GL_BGR (foreign-value "GL_BGR" GLenum))
(define GL_RGBA (foreign-value "GL_RGBA" GLenum))
(define GL_BGRA (foreign-value "GL_BGRA" GLenum))
(define GL_RED_INTEGER (foreign-value "GL_RED_INTEGER" GLenum))
(define GL_RG_INTEGER (foreign-value "GL_RG_INTEGER" GLenum))
(define GL_RGB_INTEGER (foreign-value "GL_RGB_INTEGER" GLenum))
(define GL_BGR_INTEGER (foreign-value "GL_BGR_INTEGER" GLenum))
(define GL_RGBA_INTEGER (foreign-value "GL_RGBA_INTEGER" GLenum))
(define GL_BGRA_INTEGER (foreign-value "GL_BGRA_INTEGER" GLenum))
(define GL_STENCIL_INDEX (foreign-value "GL_STENCIL_INDEX" GLenum))
(define GL_DEPTH_COMPONENT (foreign-value "GL_DEPTH_COMPONENT" GLenum))
(define GL_DEPTH_STENCIL (foreign-value "GL_DEPTH_STENCIL" GLenum))

;; types
(define GL_UNSIGNED_BYTE (foreign-value "GL_UNSIGNED_BYTE" GLenum))
(define GL_BYTE (foreign-value "GL_BYTE" GLenum))
(define GL_UNSIGNED_SHORT (foreign-value "GL_UNSIGNED_SHORT" GLenum))
(define GL_SHORT (foreign-value "GL_SHORT" GLenum))
(define GL_UNSIGNED_INT (foreign-value "GL_UNSIGNED_INT" GLenum))
(define GL_INT (foreign-value "GL_INT" GLenum))
(define GL_HALF_FLOAT (foreign-value "GL_HALF_FLOAT" GLenum))
(define GL_FLOAT (foreign-value "GL_FLOAT" GLenum))
(define GL_UNSIGNED_BYTE_3_3_2 (foreign-value "GL_UNSIGNED_BYTE_3_3_2" GLenum))
(define GL_UNSIGNED_BYTE_2_3_3_REV (foreign-value "GL_UNSIGNED_BYTE_2_3_3_REV" GLenum))
(define GL_UNSIGNED_SHORT_5_6_5 (foreign-value "GL_UNSIGNED_SHORT_5_6_5" GLenum))
(define GL_UNSIGNED_SHORT_5_6_5_REV (foreign-value "GL_UNSIGNED_SHORT_5_6_5_REV" GLenum))
(define GL_UNSIGNED_SHORT_4_4_4_4 (foreign-value "GL_UNSIGNED_SHORT_4_4_4_4" GLenum))
(define GL_UNSIGNED_SHORT_4_4_4_4_REV (foreign-value "GL_UNSIGNED_SHORT_4_4_4_4_REV" GLenum))
(define GL_UNSIGNED_SHORT_5_5_5_1 (foreign-value "GL_UNSIGNED_SHORT_5_5_5_1" GLenum))
(define GL_UNSIGNED_SHORT_1_5_5_5_REV (foreign-value "GL_UNSIGNED_SHORT_1_5_5_5_REV" GLenum))
(define GL_UNSIGNED_INT_8_8_8_8 (foreign-value "GL_UNSIGNED_INT_8_8_8_8" GLenum))
(define GL_UNSIGNED_INT_8_8_8_8_REV (foreign-value "GL_UNSIGNED_INT_8_8_8_8_REV" GLenum))
(define GL_UNSIGNED_INT_10_10_10_2 (foreign-value "GL_UNSIGNED_INT_10_10_10_2" GLenum))
(define GL_UNSIGNED_INT_2_10_10_10_REV (foreign-value "GL_UNSIGNED_INT_2_10_10_10_REV" GLenum))

;; mag and min filter values
(define GL_NEAREST (foreign-value "GL_NEAREST" GLenum))
(define GL_LINEAR (foreign-value "GL_LINEAR" GLenum))

;; wrap values
(define GL_CLAMP_TO_EDGE (foreign-value "GL_CLAMP_TO_EDGE" GLenum))
(define GL_CLAMP_TO_BORDER (foreign-value "GL_CLAMP_TO_BORDER" GLenum))
(define GL_MIRRORED_REPEAT (foreign-value "GL_MIRRORED_REPEAT" GLenum))
(define GL_REPEAT (foreign-value "GL_REPEAT" GLenum))
(define GL_MIRROR_CLAMP_TO_EDGE (foreign-value "GL_MIRROR_CLAMP_TO_EDGE" GLenum))


;; funcs
(define glGenTextures (foreign-lambda void glGenTextures size_t u32vector))
(define glBindTexture (foreign-lambda void glBindTexture GLenum unsigned-int))
(define glTexParameteri (foreign-lambda void glTexParameteri GLenum GLenum int))
(define glTexImage2D
  (foreign-lambda void glTexImage2D
    GLenum int int size_t size_t int GLenum GLenum c-pointer))
(define glTexStorage3D
  (foreign-lambda void glTexStorage3D
    GLenum size_t GLenum size_t size_t size_t))

(define glTexSubImage3D
  (foreign-lambda void glTexSubImage3D
    GLenum int int int int size_t size_t size_t GLenum GLenum c-pointer))
(define glTexSubImage3D/blob
  (foreign-lambda void glTexSubImage3D
    GLenum int int int int size_t size_t size_t GLenum GLenum blob))
(define glActiveTexture (foreign-lambda void glActiveTexture GLenum))

;; =============================================================================
;; shaders
;; =============================================================================

;; shaderTypes
(define GL_COMPUTE_SHADER (foreign-value "GL_COMPUTE_SHADER" GLenum))
(define GL_VERTEX_SHADER (foreign-value "GL_VERTEX_SHADER" GLenum))
(define GL_TESS_CONTROL_SHADER (foreign-value "GL_TESS_CONTROL_SHADER" GLenum))
(define GL_TESS_EVALUATION_SHADER (foreign-value "GL_TESS_EVALUATION_SHADER" GLenum))
(define GL_GEOMETRY_SHADER (foreign-value "GL_GEOMETRY_SHADER" GLenum))
(define GL_FRAGMENT_SHADER (foreign-value "GL_FRAGMENT_SHADER" GLenum))

;; pname
(define GL_SHADER_TYPE (foreign-value "GL_SHADER_TYPE" GLenum))
(define GL_DELETE_STATUS (foreign-value "GL_DELETE_STATUS" GLenum))
(define GL_COMPILE_STATUS (foreign-value "GL_COMPILE_STATUS" GLenum))
(define GL_INFO_LOG_LENGTH (foreign-value "GL_INFO_LOG_LENGTH" GLenum))
(define GL_SHADER_SOURCE_LENGTH (foreign-value "GL_SHADER_SOURCE_LENGTH" GLenum))

(define GL_DELETE_STATUS (foreign-value "GL_DELETE_STATUS" GLenum))
(define GL_LINK_STATUS (foreign-value "GL_LINK_STATUS" GLenum))
(define GL_VALIDATE_STATUS (foreign-value "GL_VALIDATE_STATUS" GLenum))
(define GL_INFO_LOG_LENGTH (foreign-value "GL_INFO_LOG_LENGTH" GLenum))
(define GL_ATTACHED_SHADERS (foreign-value "GL_ATTACHED_SHADERS" GLenum))
(define GL_ACTIVE_ATOMIC_COUNTER_BUFFERS (foreign-value "GL_ACTIVE_ATOMIC_COUNTER_BUFFERS" GLenum))
(define GL_ACTIVE_ATTRIBUTES (foreign-value "GL_ACTIVE_ATTRIBUTES" GLenum))
(define GL_ACTIVE_ATTRIBUTE_MAX_LENGTH (foreign-value "GL_ACTIVE_ATTRIBUTE_MAX_LENGTH" GLenum))
(define GL_ACTIVE_UNIFORMS (foreign-value "GL_ACTIVE_UNIFORMS" GLenum))
(define GL_ACTIVE_UNIFORM_BLOCKS (foreign-value "GL_ACTIVE_UNIFORM_BLOCKS" GLenum))
(define GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH (foreign-value "GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH" GLenum))
(define GL_ACTIVE_UNIFORM_MAX_LENGTH (foreign-value "GL_ACTIVE_UNIFORM_MAX_LENGTH" GLenum))
(define GL_COMPUTE_WORK_GROUP_SIZE (foreign-value "GL_COMPUTE_WORK_GROUP_SIZE" GLenum))
(define GL_PROGRAM_BINARY_LENGTH (foreign-value "GL_PROGRAM_BINARY_LENGTH" GLenum))
(define GL_TRANSFORM_FEEDBACK_BUFFER_MODE (foreign-value "GL_TRANSFORM_FEEDBACK_BUFFER_MODE" GLenum))
(define GL_TRANSFORM_FEEDBACK_VARYINGS (foreign-value "GL_TRANSFORM_FEEDBACK_VARYINGS" GLenum))
(define GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH (foreign-value "GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH" GLenum))
(define GL_GEOMETRY_VERTICES_OUT (foreign-value "GL_GEOMETRY_VERTICES_OUT" GLenum))
(define GL_GEOMETRY_INPUT_TYPE (foreign-value "GL_GEOMETRY_INPUT_TYPE" GLenum))
(define GL_GEOMETRY_OUTPUT_TYPE (foreign-value "GL_GEOMETRY_OUTPUT_TYPE" GLenum))

;; funcs
(define glCreateShader (foreign-lambda unsigned-int glCreateShader GLenum))
(define glShaderSource/single
  (foreign-lambda* void ((unsigned-int shader) (c-string str))
    "int count = 1; int len = strlen(str); glShaderSource(shader, count, (const GLchar **)&str, &len);"))
(define glCompileShader (foreign-lambda void glCompileShader unsigned-int))
(define glGetShaderiv (foreign-lambda void glGetShaderiv unsigned-int GLenum s32vector))
(define glGetShaderInfoLog (foreign-lambda void glGetShaderInfoLog unsigned-int size_t s32vector blob))
(define glDeleteShader (foreign-lambda void glDeleteShader unsigned-int))

(define glCreateProgram (foreign-lambda unsigned-int glCreateProgram))
(define glAttachShader (foreign-lambda void glAttachShader unsigned-int unsigned-int))
(define glLinkProgram (foreign-lambda void glLinkProgram unsigned-int))
(define glGetProgramiv (foreign-lambda void glGetProgramiv unsigned-int GLenum s32vector))
(define glGetProgramInfoLog (foreign-lambda void glGetProgramInfoLog unsigned-int size_t s32vector blob))
(define glUseProgram (foreign-lambda void glUseProgram unsigned-int))
(define glDeleteProgram (foreign-lambda void glDeleteProgram unsigned-int))

(define glGetUniformLocation (foreign-lambda int glGetUniformLocation unsigned-int c-string))
(define glGetAttribLocation (foreign-lambda int glGetAttribLocation unsigned-int c-string))

(define glUniform1f (foreign-lambda void glUniform1f int float))
(define glUniform1i (foreign-lambda void glUniform1i int int))
(define glUniformMatrix4fv (foreign-lambda void glUniformMatrix4fv int size_t bool f32vector))

;; =============================================================================
;; draw elements
;; =============================================================================

(define GL_POINTS (foreign-value "GL_POINTS" GLenum))
(define GL_LINE_STRIP (foreign-value "GL_LINE_STRIP" GLenum))
(define GL_LINE_LOOP (foreign-value "GL_LINE_LOOP" GLenum))
(define GL_LINES (foreign-value "GL_LINES" GLenum))
(define GL_LINE_STRIP_ADJACENCY (foreign-value "GL_LINE_STRIP_ADJACENCY" GLenum))
(define GL_LINES_ADJACENCY (foreign-value "GL_LINES_ADJACENCY" GLenum))
(define GL_TRIANGLE_STRIP (foreign-value "GL_TRIANGLE_STRIP" GLenum))
(define GL_TRIANGLE_FAN (foreign-value "GL_TRIANGLE_FAN" GLenum))
(define GL_TRIANGLES (foreign-value "GL_TRIANGLES" GLenum))
(define GL_TRIANGLE_STRIP_ADJACENCY (foreign-value "GL_TRIANGLE_STRIP_ADJACENCY" GLenum))
(define GL_TRIANGLES_ADJACENCY (foreign-value "GL_TRIANGLES_ADJACENCY" GLenum))
(define GL_PATCHES (foreign-value "GL_PATCHES" GLenum))

(define glDrawElements (foreign-lambda void glDrawElements GLenum size_t GLenum c-pointer))

)
