(module (egggame sdl) *

(import (scheme)
        (chicken base)
        (chicken syntax)
        (chicken module)
        (chicken foreign)
        (srfi-4))

(foreign-declare "#include <SDL3/SDL.h>")

;; =============================================================================
;; init functions
;; =============================================================================
(define SDL_INIT_AUDIO (foreign-value "SDL_INIT_AUDIO" unsigned-integer32))
(define SDL_INIT_VIDEO (foreign-value "SDL_INIT_VIDEO" unsigned-integer32))
(define SDL_INIT_JOYSTICK (foreign-value "SDL_INIT_JOYSTICK" unsigned-integer32))
(define SDL_INIT_HAPTIC (foreign-value "SDL_INIT_HAPTIC" unsigned-integer32))
(define SDL_INIT_GAMEPAD (foreign-value "SDL_INIT_GAMEPAD" unsigned-integer32))
(define SDL_INIT_EVENTS (foreign-value "SDL_INIT_EVENTS" unsigned-integer32))
(define SDL_INIT_SENSOR (foreign-value "SDL_INIT_SENSOR" unsigned-integer32))
(define SDL_INIT_CAMERA (foreign-value "SDL_INIT_CAMERA" unsigned-integer32))

(define SDL_Init (foreign-lambda bool SDL_Init unsigned-integer32))
(define SDL_InitSubSystem (foreign-lambda bool SDL_InitSubSystem unsigned-integer32))
(define SDL_Quit (foreign-lambda void SDL_Quit))
(define SDL_QuitSubSystem (foreign-lambda void SDL_QuitSubSystem unsigned-integer32))

(define SDL_GetError (foreign-lambda c-string SDL_GetError))

;; =============================================================================
;; video functions
;; =============================================================================

(define SDL_WINDOW_FULLSCREEN (foreign-value "SDL_WINDOW_FULLSCREEN" unsigned-integer64))
(define SDL_WINDOW_OPENGL (foreign-value "SDL_WINDOW_OPENGL" unsigned-integer64))
(define SDL_WINDOW_OCCLUDED (foreign-value "SDL_WINDOW_OCCLUDED" unsigned-integer64))
(define SDL_WINDOW_HIDDEN (foreign-value "SDL_WINDOW_HIDDEN" unsigned-integer64))
(define SDL_WINDOW_BORDERLESS (foreign-value "SDL_WINDOW_BORDERLESS" unsigned-integer64))
(define SDL_WINDOW_RESIZABLE (foreign-value "SDL_WINDOW_RESIZABLE" unsigned-integer64))
(define SDL_WINDOW_MINIMIZED (foreign-value "SDL_WINDOW_MINIMIZED" unsigned-integer64))
(define SDL_WINDOW_MAXIMIZED (foreign-value "SDL_WINDOW_MAXIMIZED" unsigned-integer64))
(define SDL_WINDOW_MOUSE_GRABBED (foreign-value "SDL_WINDOW_MOUSE_GRABBED" unsigned-integer64))
(define SDL_WINDOW_INPUT_FOCUS (foreign-value "SDL_WINDOW_INPUT_FOCUS" unsigned-integer64))
(define SDL_WINDOW_MOUSE_FOCUS (foreign-value "SDL_WINDOW_MOUSE_FOCUS" unsigned-integer64))
(define SDL_WINDOW_EXTERNAL (foreign-value "SDL_WINDOW_EXTERNAL" unsigned-integer64))
(define SDL_WINDOW_MODAL (foreign-value "SDL_WINDOW_MODAL" unsigned-integer64))
(define SDL_WINDOW_HIGH_PIXEL_DENSITY (foreign-value "SDL_WINDOW_HIGH_PIXEL_DENSITY" unsigned-integer64))
(define SDL_WINDOW_MOUSE_CAPTURE (foreign-value "SDL_WINDOW_MOUSE_CAPTURE" unsigned-integer64))
(define SDL_WINDOW_MOUSE_RELATIVE_MODE (foreign-value "SDL_WINDOW_MOUSE_RELATIVE_MODE" unsigned-integer64))
(define SDL_WINDOW_ALWAYS_ON_TOP (foreign-value "SDL_WINDOW_ALWAYS_ON_TOP" unsigned-integer64))
(define SDL_WINDOW_UTILITY (foreign-value "SDL_WINDOW_UTILITY" unsigned-integer64))
(define SDL_WINDOW_TOOLTIP (foreign-value "SDL_WINDOW_TOOLTIP" unsigned-integer64))
(define SDL_WINDOW_POPUP_MENU (foreign-value "SDL_WINDOW_POPUP_MENU" unsigned-integer64))
(define SDL_WINDOW_KEYBOARD_GRABBED (foreign-value "SDL_WINDOW_KEYBOARD_GRABBED" unsigned-integer64))
(define SDL_WINDOW_VULKAN (foreign-value "SDL_WINDOW_VULKAN" unsigned-integer64))
(define SDL_WINDOW_METAL (foreign-value "SDL_WINDOW_METAL" unsigned-integer64))
(define SDL_WINDOW_TRANSPARENT (foreign-value "SDL_WINDOW_TRANSPARENT" unsigned-integer64))
(define SDL_WINDOW_NOT_FOCUSABLE (foreign-value "SDL_WINDOW_NOT_FOCUSABLE" unsigned-integer64))

(define SDL_CreateWindow
  (foreign-lambda c-pointer SDL_CreateWindow
    c-string int int unsigned-integer64))

;; =============================================================================
;; opengl stuff
;; =============================================================================

(define SDL_GL_CreateContext
  (foreign-lambda c-pointer SDL_GL_CreateContext c-pointer))

(define sizeof-int (foreign-value "sizeof(int)" int))

(define SDL_GL_RED_SIZE (foreign-value "SDL_GL_RED_SIZE" int))
(define SDL_GL_GREEN_SIZE (foreign-value "SDL_GL_GREEN_SIZE" int))
(define SDL_GL_BLUE_SIZE (foreign-value "SDL_GL_BLUE_SIZE" int))
(define SDL_GL_ALPHA_SIZE (foreign-value "SDL_GL_ALPHA_SIZE" int))
(define SDL_GL_BUFFER_SIZE (foreign-value "SDL_GL_BUFFER_SIZE" int))
(define SDL_GL_DOUBLEBUFFER (foreign-value "SDL_GL_DOUBLEBUFFER" int))
(define SDL_GL_DEPTH_SIZE (foreign-value "SDL_GL_DEPTH_SIZE" int))
(define SDL_GL_STENCIL_SIZE (foreign-value "SDL_GL_STENCIL_SIZE" int))
(define SDL_GL_ACCUM_RED_SIZE (foreign-value "SDL_GL_ACCUM_RED_SIZE" int))
(define SDL_GL_ACCUM_GREEN_SIZE (foreign-value "SDL_GL_ACCUM_GREEN_SIZE" int))
(define SDL_GL_ACCUM_BLUE_SIZE (foreign-value "SDL_GL_ACCUM_BLUE_SIZE" int))
(define SDL_GL_ACCUM_ALPHA_SIZE (foreign-value "SDL_GL_ACCUM_ALPHA_SIZE" int))
(define SDL_GL_STEREO (foreign-value "SDL_GL_STEREO" int))
(define SDL_GL_MULTISAMPLEBUFFERS (foreign-value "SDL_GL_MULTISAMPLEBUFFERS" int))
(define SDL_GL_MULTISAMPLESAMPLES (foreign-value "SDL_GL_MULTISAMPLESAMPLES" int))
(define SDL_GL_ACCELERATED_VISUAL (foreign-value "SDL_GL_ACCELERATED_VISUAL" int))
(define SDL_GL_RETAINED_BACKING (foreign-value "SDL_GL_RETAINED_BACKING" int))
(define SDL_GL_CONTEXT_MAJOR_VERSION (foreign-value "SDL_GL_CONTEXT_MAJOR_VERSION" int))
(define SDL_GL_CONTEXT_MINOR_VERSION (foreign-value "SDL_GL_CONTEXT_MINOR_VERSION" int))
(define SDL_GL_CONTEXT_FLAGS (foreign-value "SDL_GL_CONTEXT_FLAGS" int))
(define SDL_GL_CONTEXT_PROFILE_MASK (foreign-value "SDL_GL_CONTEXT_PROFILE_MASK" int))
(define SDL_GL_SHARE_WITH_CURRENT_CONTEXT (foreign-value "SDL_GL_SHARE_WITH_CURRENT_CONTEXT" int))
(define SDL_GL_FRAMEBUFFER_SRGB_CAPABLE (foreign-value "SDL_GL_FRAMEBUFFER_SRGB_CAPABLE" int))
(define SDL_GL_CONTEXT_RELEASE_BEHAVIOR (foreign-value "SDL_GL_CONTEXT_RELEASE_BEHAVIOR" int))
(define SDL_GL_CONTEXT_RESET_NOTIFICATION (foreign-value "SDL_GL_CONTEXT_RESET_NOTIFICATION" int))
(define SDL_GL_CONTEXT_NO_ERROR (foreign-value "SDL_GL_CONTEXT_NO_ERROR" int))
(define SDL_GL_FLOATBUFFERS (foreign-value "SDL_GL_FLOATBUFFERS" int))
(define SDL_GL_EGL_PLATFORM (foreign-value "SDL_GL_EGL_PLATFORM" int))
(define SDL_GL_CONTEXT_DEBUG_FLAG (foreign-value "SDL_GL_CONTEXT_DEBUG_FLAG" (enum SDL_GLattr)))
(define SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG (foreign-value "SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG" (enum SDL_GLattr)))
(define SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG (foreign-value "SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG" (enum SDL_GLattr)))
(define SDL_GL_CONTEXT_RESET_ISOLATION_FLAG (foreign-value "SDL_GL_CONTEXT_RESET_ISOLATION_FLAG" (enum SDL_GLattr)))

(define (SDL_GL_GetAttribute attr)
  (unless (= sizeof-int 4) (error "this needs to be rewritten"))
  (let ((value (s32vector 234)))
    (and ((foreign-lambda* bool (((enum "SDL_GLAttr") attr) (s32vector value))
            "C_return(SDL_GL_GetAttribute(attr, value));")
          attr value)
         (s32vector-ref value 0))))

(define SDL_GL_SetAttribute (foreign-lambda bool SDL_GL_SetAttribute int int))

(define SDL_GL_SetSwapInterval (foreign-lambda bool SDL_GL_SetSwapInterval int))
(define SDL_GL_SwapWindow (foreign-lambda bool SDL_GL_SwapWindow c-pointer))

;; =============================================================================
;; event stuff
;; =============================================================================

(define SDL_PollEvent
  (foreign-lambda* bool ((u8vector ev))
    "C_return(SDL_PollEvent((SDL_Event*)ev));"))

(define sizeof-SDL_Event (foreign-value "sizeof(SDL_Event)" int))

(define (make-SDL_Event)
  (make-u8vector sizeof-SDL_Event))

(define SDL_Event-type
  (foreign-lambda* unsigned-integer32 ((u8vector ev))
    "C_return(((SDL_Event*)ev)->type);"))

(define SDL_EVENT_FIRST (foreign-value "SDL_EVENT_FIRST" unsigned-integer32))
(define SDL_EVENT_QUIT (foreign-value "SDL_EVENT_QUIT" unsigned-integer32))
(define SDL_EVENT_TERMINATING (foreign-value "SDL_EVENT_TERMINATING" unsigned-integer32))
(define SDL_EVENT_LOW_MEMORY (foreign-value "SDL_EVENT_LOW_MEMORY" unsigned-integer32))
(define SDL_EVENT_WILL_ENTER_BACKGROUND (foreign-value "SDL_EVENT_WILL_ENTER_BACKGROUND" unsigned-integer32))
(define SDL_EVENT_DID_ENTER_BACKGROUND (foreign-value "SDL_EVENT_DID_ENTER_BACKGROUND" unsigned-integer32))
(define SDL_EVENT_WILL_ENTER_FOREGROUND (foreign-value "SDL_EVENT_WILL_ENTER_FOREGROUND" unsigned-integer32))
(define SDL_EVENT_DID_ENTER_FOREGROUND (foreign-value "SDL_EVENT_DID_ENTER_FOREGROUND" unsigned-integer32))
(define SDL_EVENT_LOCALE_CHANGED (foreign-value "SDL_EVENT_LOCALE_CHANGED" unsigned-integer32))
(define SDL_EVENT_SYSTEM_THEME_CHANGED (foreign-value "SDL_EVENT_SYSTEM_THEME_CHANGED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_ORIENTATION (foreign-value "SDL_EVENT_DISPLAY_ORIENTATION" unsigned-integer32))
(define SDL_EVENT_DISPLAY_ADDED (foreign-value "SDL_EVENT_DISPLAY_ADDED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_REMOVED (foreign-value "SDL_EVENT_DISPLAY_REMOVED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_MOVED (foreign-value "SDL_EVENT_DISPLAY_MOVED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED (foreign-value "SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED (foreign-value "SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED (foreign-value "SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED" unsigned-integer32))
(define SDL_EVENT_DISPLAY_ORIENTATION (foreign-value "SDL_EVENT_DISPLAY_ORIENTATION" unsigned-integer32))
(define SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED (foreign-value "SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_SHOWN (foreign-value "SDL_EVENT_WINDOW_SHOWN" unsigned-integer32))
(define SDL_EVENT_WINDOW_HIDDEN (foreign-value "SDL_EVENT_WINDOW_HIDDEN" unsigned-integer32))
(define SDL_EVENT_WINDOW_EXPOSED (foreign-value "SDL_EVENT_WINDOW_EXPOSED" unsigned-integer32))
(define SDL_EVENT_WINDOW_MOVED (foreign-value "SDL_EVENT_WINDOW_MOVED" unsigned-integer32))
(define SDL_EVENT_WINDOW_RESIZED (foreign-value "SDL_EVENT_WINDOW_RESIZED" unsigned-integer32))
(define SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED (foreign-value "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_METAL_VIEW_RESIZED (foreign-value "SDL_EVENT_WINDOW_METAL_VIEW_RESIZED" unsigned-integer32))
(define SDL_EVENT_WINDOW_MINIMIZED (foreign-value "SDL_EVENT_WINDOW_MINIMIZED" unsigned-integer32))
(define SDL_EVENT_WINDOW_MAXIMIZED (foreign-value "SDL_EVENT_WINDOW_MAXIMIZED" unsigned-integer32))
(define SDL_EVENT_WINDOW_RESTORED (foreign-value "SDL_EVENT_WINDOW_RESTORED" unsigned-integer32))
(define SDL_EVENT_WINDOW_MOUSE_ENTER (foreign-value "SDL_EVENT_WINDOW_MOUSE_ENTER" unsigned-integer32))
(define SDL_EVENT_WINDOW_MOUSE_LEAVE (foreign-value "SDL_EVENT_WINDOW_MOUSE_LEAVE" unsigned-integer32))
(define SDL_EVENT_WINDOW_FOCUS_GAINED (foreign-value "SDL_EVENT_WINDOW_FOCUS_GAINED" unsigned-integer32))
(define SDL_EVENT_WINDOW_FOCUS_LOST (foreign-value "SDL_EVENT_WINDOW_FOCUS_LOST" unsigned-integer32))
(define SDL_EVENT_WINDOW_CLOSE_REQUESTED (foreign-value "SDL_EVENT_WINDOW_CLOSE_REQUESTED" unsigned-integer32))
(define SDL_EVENT_WINDOW_HIT_TEST (foreign-value "SDL_EVENT_WINDOW_HIT_TEST" unsigned-integer32))
(define SDL_EVENT_WINDOW_ICCPROF_CHANGED (foreign-value "SDL_EVENT_WINDOW_ICCPROF_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_DISPLAY_CHANGED (foreign-value "SDL_EVENT_WINDOW_DISPLAY_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED (foreign-value "SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_SAFE_AREA_CHANGED (foreign-value "SDL_EVENT_WINDOW_SAFE_AREA_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_OCCLUDED (foreign-value "SDL_EVENT_WINDOW_OCCLUDED" unsigned-integer32))
(define SDL_EVENT_WINDOW_ENTER_FULLSCREEN (foreign-value "SDL_EVENT_WINDOW_ENTER_FULLSCREEN" unsigned-integer32))
(define SDL_EVENT_WINDOW_LEAVE_FULLSCREEN (foreign-value "SDL_EVENT_WINDOW_LEAVE_FULLSCREEN" unsigned-integer32))
(define SDL_EVENT_WINDOW_DESTROYED (foreign-value "SDL_EVENT_WINDOW_DESTROYED" unsigned-integer32))
(define SDL_EVENT_WINDOW_HDR_STATE_CHANGED (foreign-value "SDL_EVENT_WINDOW_HDR_STATE_CHANGED" unsigned-integer32))
(define SDL_EVENT_WINDOW_SHOWN (foreign-value "SDL_EVENT_WINDOW_SHOWN" unsigned-integer32))
(define SDL_EVENT_WINDOW_HDR_STATE_CHANGED (foreign-value "SDL_EVENT_WINDOW_HDR_STATE_CHANGED" unsigned-integer32))
(define SDL_EVENT_KEY_DOWN (foreign-value "SDL_EVENT_KEY_DOWN" unsigned-integer32))
(define SDL_EVENT_KEY_UP (foreign-value "SDL_EVENT_KEY_UP" unsigned-integer32))
(define SDL_EVENT_TEXT_EDITING (foreign-value "SDL_EVENT_TEXT_EDITING" unsigned-integer32))
(define SDL_EVENT_TEXT_INPUT (foreign-value "SDL_EVENT_TEXT_INPUT" unsigned-integer32))
(define SDL_EVENT_KEYMAP_CHANGED (foreign-value "SDL_EVENT_KEYMAP_CHANGED" unsigned-integer32))
(define SDL_EVENT_KEYBOARD_ADDED (foreign-value "SDL_EVENT_KEYBOARD_ADDED" unsigned-integer32))
(define SDL_EVENT_KEYBOARD_REMOVED (foreign-value "SDL_EVENT_KEYBOARD_REMOVED" unsigned-integer32))
(define SDL_EVENT_TEXT_EDITING_CANDIDATES (foreign-value "SDL_EVENT_TEXT_EDITING_CANDIDATES" unsigned-integer32))
(define SDL_EVENT_MOUSE_MOTION (foreign-value "SDL_EVENT_MOUSE_MOTION" unsigned-integer32))
(define SDL_EVENT_MOUSE_BUTTON_DOWN (foreign-value "SDL_EVENT_MOUSE_BUTTON_DOWN" unsigned-integer32))
(define SDL_EVENT_MOUSE_BUTTON_UP (foreign-value "SDL_EVENT_MOUSE_BUTTON_UP" unsigned-integer32))
(define SDL_EVENT_MOUSE_WHEEL (foreign-value "SDL_EVENT_MOUSE_WHEEL" unsigned-integer32))
(define SDL_EVENT_MOUSE_ADDED (foreign-value "SDL_EVENT_MOUSE_ADDED" unsigned-integer32))
(define SDL_EVENT_MOUSE_REMOVED (foreign-value "SDL_EVENT_MOUSE_REMOVED" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_AXIS_MOTION (foreign-value "SDL_EVENT_JOYSTICK_AXIS_MOTION" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_BALL_MOTION (foreign-value "SDL_EVENT_JOYSTICK_BALL_MOTION" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_HAT_MOTION (foreign-value "SDL_EVENT_JOYSTICK_HAT_MOTION" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_BUTTON_DOWN (foreign-value "SDL_EVENT_JOYSTICK_BUTTON_DOWN" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_BUTTON_UP (foreign-value "SDL_EVENT_JOYSTICK_BUTTON_UP" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_ADDED (foreign-value "SDL_EVENT_JOYSTICK_ADDED" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_REMOVED (foreign-value "SDL_EVENT_JOYSTICK_REMOVED" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_BATTERY_UPDATED (foreign-value "SDL_EVENT_JOYSTICK_BATTERY_UPDATED" unsigned-integer32))
(define SDL_EVENT_JOYSTICK_UPDATE_COMPLETE (foreign-value "SDL_EVENT_JOYSTICK_UPDATE_COMPLETE" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_AXIS_MOTION (foreign-value "SDL_EVENT_GAMEPAD_AXIS_MOTION" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_BUTTON_DOWN (foreign-value "SDL_EVENT_GAMEPAD_BUTTON_DOWN" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_BUTTON_UP (foreign-value "SDL_EVENT_GAMEPAD_BUTTON_UP" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_ADDED (foreign-value "SDL_EVENT_GAMEPAD_ADDED" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_REMOVED (foreign-value "SDL_EVENT_GAMEPAD_REMOVED" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_REMAPPED (foreign-value "SDL_EVENT_GAMEPAD_REMAPPED" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN (foreign-value "SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION (foreign-value "SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_TOUCHPAD_UP (foreign-value "SDL_EVENT_GAMEPAD_TOUCHPAD_UP" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_SENSOR_UPDATE (foreign-value "SDL_EVENT_GAMEPAD_SENSOR_UPDATE" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_UPDATE_COMPLETE (foreign-value "SDL_EVENT_GAMEPAD_UPDATE_COMPLETE" unsigned-integer32))
(define SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED (foreign-value "SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED" unsigned-integer32))
(define SDL_EVENT_FINGER_DOWN (foreign-value "SDL_EVENT_FINGER_DOWN" unsigned-integer32))
(define SDL_EVENT_FINGER_UP (foreign-value "SDL_EVENT_FINGER_UP" unsigned-integer32))
(define SDL_EVENT_FINGER_MOTION (foreign-value "SDL_EVENT_FINGER_MOTION" unsigned-integer32))
(define SDL_EVENT_FINGER_CANCELED (foreign-value "SDL_EVENT_FINGER_CANCELED" unsigned-integer32))
(define SDL_EVENT_CLIPBOARD_UPDATE (foreign-value "SDL_EVENT_CLIPBOARD_UPDATE" unsigned-integer32))
(define SDL_EVENT_DROP_FILE (foreign-value "SDL_EVENT_DROP_FILE" unsigned-integer32))
(define SDL_EVENT_DROP_TEXT (foreign-value "SDL_EVENT_DROP_TEXT" unsigned-integer32))
(define SDL_EVENT_DROP_BEGIN (foreign-value "SDL_EVENT_DROP_BEGIN" unsigned-integer32))
(define SDL_EVENT_DROP_COMPLETE (foreign-value "SDL_EVENT_DROP_COMPLETE" unsigned-integer32))
(define SDL_EVENT_DROP_POSITION (foreign-value "SDL_EVENT_DROP_POSITION" unsigned-integer32))
(define SDL_EVENT_AUDIO_DEVICE_ADDED (foreign-value "SDL_EVENT_AUDIO_DEVICE_ADDED" unsigned-integer32))
(define SDL_EVENT_AUDIO_DEVICE_REMOVED (foreign-value "SDL_EVENT_AUDIO_DEVICE_REMOVED" unsigned-integer32))
(define SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED (foreign-value "SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED" unsigned-integer32))
(define SDL_EVENT_SENSOR_UPDATE (foreign-value "SDL_EVENT_SENSOR_UPDATE" unsigned-integer32))
(define SDL_EVENT_PEN_PROXIMITY_IN (foreign-value "SDL_EVENT_PEN_PROXIMITY_IN" unsigned-integer32))
(define SDL_EVENT_PEN_PROXIMITY_OUT (foreign-value "SDL_EVENT_PEN_PROXIMITY_OUT" unsigned-integer32))
(define SDL_EVENT_PEN_DOWN (foreign-value "SDL_EVENT_PEN_DOWN" unsigned-integer32))
(define SDL_EVENT_PEN_UP (foreign-value "SDL_EVENT_PEN_UP" unsigned-integer32))
(define SDL_EVENT_PEN_BUTTON_DOWN (foreign-value "SDL_EVENT_PEN_BUTTON_DOWN" unsigned-integer32))
(define SDL_EVENT_PEN_BUTTON_UP (foreign-value "SDL_EVENT_PEN_BUTTON_UP" unsigned-integer32))
(define SDL_EVENT_PEN_MOTION (foreign-value "SDL_EVENT_PEN_MOTION" unsigned-integer32))
(define SDL_EVENT_PEN_AXIS (foreign-value "SDL_EVENT_PEN_AXIS" unsigned-integer32))
(define SDL_EVENT_CAMERA_DEVICE_ADDED (foreign-value "SDL_EVENT_CAMERA_DEVICE_ADDED" unsigned-integer32))
(define SDL_EVENT_CAMERA_DEVICE_REMOVED (foreign-value "SDL_EVENT_CAMERA_DEVICE_REMOVED" unsigned-integer32))
(define SDL_EVENT_CAMERA_DEVICE_APPROVED (foreign-value "SDL_EVENT_CAMERA_DEVICE_APPROVED" unsigned-integer32))
(define SDL_EVENT_CAMERA_DEVICE_DENIED (foreign-value "SDL_EVENT_CAMERA_DEVICE_DENIED" unsigned-integer32))
(define SDL_EVENT_RENDER_TARGETS_RESET (foreign-value "SDL_EVENT_RENDER_TARGETS_RESET" unsigned-integer32))
(define SDL_EVENT_RENDER_DEVICE_RESET (foreign-value "SDL_EVENT_RENDER_DEVICE_RESET" unsigned-integer32))
(define SDL_EVENT_RENDER_DEVICE_LOST (foreign-value "SDL_EVENT_RENDER_DEVICE_LOST" unsigned-integer32))
(define SDL_EVENT_PRIVATE0 (foreign-value "SDL_EVENT_PRIVATE0" unsigned-integer32))
(define SDL_EVENT_PRIVATE1 (foreign-value "SDL_EVENT_PRIVATE1" unsigned-integer32))
(define SDL_EVENT_PRIVATE2 (foreign-value "SDL_EVENT_PRIVATE2" unsigned-integer32))
(define SDL_EVENT_PRIVATE3 (foreign-value "SDL_EVENT_PRIVATE3" unsigned-integer32))
(define SDL_EVENT_POLL_SENTINEL (foreign-value "SDL_EVENT_POLL_SENTINEL" unsigned-integer32))
(define SDL_EVENT_LAST (foreign-value "SDL_EVENT_LAST" unsigned-integer32))
(define SDL_EVENT_USER (foreign-value "SDL_EVENT_USER" unsigned-integer32))
(define SDL_EVENT_LAST (foreign-value "SDL_EVENT_LAST" unsigned-integer32))


;; =============================================================================
;; time stuff
;; =============================================================================

(define-foreign-type SDL_Time integer64)
(define-foreign-type SDL_Time* s64vector)

(define SDL_GetCurrentTime (foreign-lambda bool SDL_GetCurrentTime SDL_Time*))

(define (SDL_GetCurrentTime/ret #!optional (store (s64vector 4)))
  (and (SDL_GetCurrentTime store)
       store))

(define SDL_GetTicks (foreign-lambda unsigned-integer64 SDL_GetTicks))
(define SDL_Delay (foreign-lambda void SDL_Delay unsigned-integer32))

)
